#!/usr/bin/env bash
# Regenerate the API types from the vendored OpenAPI spec.
#
# Pinned tools: datamodel-code-generator, plus the two formatters it shells
# out to. All three are pinned in the variables below and passed to `uvx`,
# which builds the environment from those exact versions rather than
# resolving whatever the index offers today.
#
# WHY THE FORMATTERS ARE PINNED TOO. datamodel-code-generator does not lay
# out the file it writes; black and isort do, and they arrive as its own
# loose dependencies. Unpinned, a newer black that wraps one Literal
# differently rewrites this file on a run nobody asked for, and the diff
# lands in whichever spec-sync PR happened to run next — attached to a spec
# change that did not cause it. The predecessor of this script had exactly
# that hole and said so.
#
# WHAT THIS WRITES is ONE file of TYPES — `src/ringivo/_generated_types.py`,
# one `TypedDict` per schema in the OpenAPI description. There is no
# generated runtime here and no generated client: a `TypedDict` is a plain
# `dict` once the interpreter has it, so the file adds no behaviour and no
# import cost. It does add ONE dependency, on every interpreter:
# `typing_extensions`, 4.10 or newer. The hand-written layer in
# src/ringivo/*.py is the whole client. Nothing generated crosses the public
# boundary — see models.py.
#
# The file IS committed, and pyright checks it like any other source file.
# Committed so a spec-sync diff stays reviewable in a PR; checked because a
# generated file excluded from the type checker is a claim about types
# rather than a guarantee of them.
#
# THIS REPO'S pyproject.toml IS A CODEGEN INPUT. black and isort discover
# configuration by walking up from the file they are formatting, and that
# walk reaches this repo's pyproject.toml. There is no [tool.black] or
# [tool.isort] table there today, so both run on their defaults — but ADD
# one and it silently changes what the next run of this script writes.
# Verified rather than assumed: a temporary `[tool.black] line-length = 60`
# in pyproject.toml re-wrapped 4 lines of the generated file into 13, in 4
# places. If you add either table, regenerate and diff before committing.
set -euo pipefail

GENERATOR_VERSION="0.74.0"
BLACK_VERSION="26.5.1"
ISORT_VERSION="8.0.1"

cd "$(dirname "${BASH_SOURCE[0]}")/.."

SPEC_PATH="spec/openapi.yaml"
DEST="src/ringivo/_generated_types.py"

if [[ ! -f "${SPEC_PATH}" ]]; then
  echo "generate.sh: ${SPEC_PATH} not found — vendor the spec first" >&2
  exit 1
fi

mkdir -p "$(dirname "${DEST}")"

# Prepended ahead of the generator's own `# generated by` marker, so the
# file opens with a real module docstring and still carries the machine
# banner underneath it.
HEADER=$(cat <<'EOF'
"""The vendored spec's schemas, as types. Machine-written — do not edit.

Each `TypedDict` below describes one JSON shape from spec/openapi.yaml, and
describes it at TYPE-CHECK TIME ONLY: a `TypedDict` is a plain `dict` at
runtime, so this module defines no behaviour and constructs nothing. It is
not imported by `ringivo/__init__.py`, so it costs an ordinary caller
nothing.

Nothing generated crosses the public boundary — `models.py` owns the frozen
objects this client hands back, and it reads the wire defensively rather
than trusting these shapes. What these types are FOR is reading: they are
the machine-checked record of what the API sends and accepts, for anyone
reaching past the wrapped surface with `Ringivo.request()`.

Regenerate with scripts/generate.sh, which overwrites this file whole.
"""
EOF
)

# `--target-python-version 3.10` is this package's own floor. It used to be
# described here as deciding where `NotRequired` comes from — `typing` only
# has it from 3.11 — but that stopped being the operative reason: the
# generator writes `from typing_extensions import ...` for EVERY member it
# needs, on every target, and the spec's `additionalProperties: false` now
# makes it emit `TypedDict(closed=True)`, which no stdlib `typing` carries at
# any version. So pyproject.toml declares typing-extensions unconditionally,
# floored at 4.10 — the lowest release that accepts `closed=`. If a
# regeneration changes what this file imports, re-probe that floor by hand.
# The `lowest-deps` job in .github/workflows/ci.yml installs whatever floor
# is declared and fails when it is too low, but it cannot tell you what the
# right one is — only a probe against each release can.
#
# `--disable-timestamp` is what makes a re-run reproducible. With the
# timestamp left on, every run rewrites line 3 and the file is permanently
# dirty.
uvx --from "datamodel-code-generator==${GENERATOR_VERSION}" \
    --with "black==${BLACK_VERSION}" \
    --with "isort==${ISORT_VERSION}" \
    datamodel-codegen \
  --input "${SPEC_PATH}" \
  --input-file-type openapi \
  --output "${DEST}" \
  --output-model-type typing.TypedDict \
  --target-python-version 3.10 \
  --disable-timestamp \
  --enable-version-header \
  --formatters black isort \
  --custom-file-header "${HEADER}" \
  --custom-file-header-mode prepend

echo "generate.sh: wrote ${DEST} from datamodel-code-generator ${GENERATOR_VERSION}"
