#!/usr/bin/env bash
# Regenerate the Ringivo API client from the vendored OpenAPI spec.
#
# Pinned tool: openapi-python-client 0.29.0 (matches the version upstream
# CI smokes the spec against).
# Bump the pin above AND in this script together; do not let them drift.
#
# Flow: uvx generates a fresh package into build/_gen (git-ignored scratch
# space), then rsync mirrors it into src/ringivo/_generated/, which IS
# committed — spec-sync diffs stay reviewable in PRs.
set -euo pipefail

GENERATOR_VERSION="0.29.0"

cd "$(dirname "${BASH_SOURCE[0]}")/.."

SPEC_PATH="spec/openapi.yaml"
BUILD_DIR="build/_gen"
DEST_DIR="src/ringivo/_generated"

if [[ ! -f "${SPEC_PATH}" ]]; then
  echo "generate.sh: ${SPEC_PATH} not found — vendor the spec first" >&2
  exit 1
fi

rm -rf "${BUILD_DIR}"
mkdir -p "$(dirname "${BUILD_DIR}")"

uvx "openapi-python-client@${GENERATOR_VERSION}" generate \
  --path "${SPEC_PATH}" \
  --output-path "${BUILD_DIR}" \
  --meta none

rm -rf "${DEST_DIR}"
mkdir -p "${DEST_DIR}"

rsync -a --delete \
  --exclude ".ruff_cache" \
  --exclude "__pycache__" \
  "${BUILD_DIR}/" "${DEST_DIR}/"

cat > "${DEST_DIR}/GENERATED_BY.txt" <<EOF
Generated by openapi-python-client ${GENERATOR_VERSION}
Source spec: ${SPEC_PATH}
Regenerate with: scripts/generate.sh
Do not hand-edit files under this directory — they are overwritten on the
next run.
EOF

echo "generate.sh: wrote ${DEST_DIR} from openapi-python-client ${GENERATOR_VERSION}"
