"""The vendored spec's schemas, as types. Machine-written — do not edit.

Each `TypedDict` below describes one JSON shape from spec/openapi.yaml, and
describes it at TYPE-CHECK TIME ONLY: a `TypedDict` is a plain `dict` at
runtime, so this module defines no behaviour and constructs nothing. It is
not imported by `ringivo/__init__.py`, so it costs an ordinary caller
nothing.

Nothing generated crosses the public boundary — `models.py` owns the frozen
objects this client hands back, and it reads the wire defensively rather
than trusting these shapes. What these types are FOR is reading: they are
the machine-checked record of what the API sends and accepts, for anyone
reaching past the wrapped surface with `Ringivo.request()`.

Regenerate with scripts/generate.sh, which overwrites this file whole.
"""
from __future__ import annotations

#
# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   version:   0.74.0

from typing import Any, Literal, TypeAlias

from typing_extensions import NotRequired, TypedDict


class OauthTokenRequest(TypedDict):
    grant_type: Literal['client_credentials']
    client_id: NotRequired[str]
    client_secret: NotRequired[str]
    tenant: str
    customer: NotRequired[str | None]
    scope: str


class OauthTokenResponse(TypedDict):
    access_token: str
    token_type: str
    expires_in: int
    scope: NotRequired[str]
    scopes: list[str]


class OauthError(TypedDict):
    error: str
    error_description: str
    hint: NotRequired[str]


class ResourceIdentifier(TypedDict):
    type: str
    id: str


class ResourceLinks(TypedDict):
    self: NotRequired[str]


class CollectionLinks(TypedDict):
    self: NotRequired[str | None]
    first: NotRequired[str]
    prev: NotRequired[str]
    next: NotRequired[str]


class PageMeta(TypedDict):
    size: int
    nextCursor: str | None
    total: NotRequired[int]


class DocumentMeta(TypedDict):
    page: NotRequired[PageMeta]


class Page(TypedDict):
    cursor: NotRequired[str]


class ResourceMeta(TypedDict):
    page: NotRequired[Page]


class RelationshipToOne(TypedDict):
    links: NotRequired[ResourceLinks]
    data: NotRequired[ResourceIdentifier | None]


class RelationshipToMany(TypedDict):
    links: NotRequired[ResourceLinks]
    data: NotRequired[list[ResourceIdentifier]]


class ErrorSource(TypedDict):
    pointer: NotRequired[str]
    parameter: NotRequired[str]


ErrorCode: TypeAlias = Literal[
    'validation_failed',
    'caller_id_not_permitted',
    'document_too_large',
    'too_many_pages',
    'unsupported_media_type',
    'fax_account_suspended',
    'rate_limited',
    'not_found',
    'forbidden',
    'internal_error',
]


FaxDirection: TypeAlias = Literal['inbound', 'outbound']


FaxStatus: TypeAlias = Literal[
    'queued',
    'converting',
    'sending',
    'delivered',
    'partial',
    'cancelled',
    'received',
    'failed',
]


FaxFailureCode: TypeAlias = (
    Literal[
        'busy',
        'no_answer',
        'no_fax_tone',
        'negotiation_failed',
        'line_quality',
        'line_dropped',
        'incompatible',
        'document_error',
        'invalid_number',
        'carrier_rejected',
        'internal_error',
    ]
    | None
)


FaxAccountStatus: TypeAlias = Literal['active', 'suspended']


FaxResolution: TypeAlias = Literal['fine', 'standard']


WebhookScopeType: TypeAlias = Literal['tenant', 'customer', 'fax_account']


WebhookEventType: TypeAlias = Literal[
    'fax.received',
    'fax.queued',
    'fax.converting',
    'fax.sending',
    'fax.delivered',
    'fax.partial',
    'fax.failed',
    'fax.cancelled',
    'message.received',
    'port_order.bill_extraction_settled',
    'port_order.status_changed',
]


WebhookDeliveryStatus: TypeAlias = Literal['pending', 'dead']


Tags: TypeAlias = dict[str, Any] | None


CoverPage: TypeAlias = dict[str, Any] | None


class FaxDocumentMetadata(TypedDict):
    kind: NotRequired[Literal['source', 'tiff', 'pdf', 'thumb']]
    ordinal: NotRequired[int]
    contentType: NotRequired[str | None]
    byteSize: NotRequired[int | None]
    sha256: NotRequired[str | None]
    pages: NotRequired[int | None]


FaxAttributes = TypedDict(
    'FaxAttributes',
    {
        'direction': NotRequired[FaxDirection],
        'status': NotRequired[FaxStatus],
        'failureCode': NotRequired[FaxFailureCode],
        'from': NotRequired[str | None],
        'to': NotRequired[str | None],
        'pagesTotal': NotRequired[int | None],
        'pagesTransferred': NotRequired[int | None],
        'partial': NotRequired[bool | None],
        'attemptCount': NotRequired[int | None],
        'resolution': NotRequired[str | None],
        'clientReference': NotRequired[str | None],
        'coverPage': NotRequired[CoverPage],
        'read': NotRequired[bool],
        'archived': NotRequired[bool],
        'tags': NotRequired[Tags],
        'documents': NotRequired[list[FaxDocumentMetadata]],
        'createdAt': NotRequired[str | None],
        'completedAt': NotRequired[str | None],
    },
)


class FaxRelationships(TypedDict):
    faxAccount: NotRequired[RelationshipToOne]
    attempts: NotRequired[RelationshipToMany]


class FaxResource(TypedDict):
    type: Literal['faxes']
    id: str
    attributes: NotRequired[FaxAttributes]
    relationships: NotRequired[FaxRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class FaxAttemptAttributes(TypedDict):
    attemptNo: NotRequired[int | None]
    transportProfile: NotRequired[dict[str, Any] | None]
    startedAt: NotRequired[str | None]
    answeredAt: NotRequired[str | None]
    endedAt: NotRequired[str | None]
    billableMs: NotRequired[int | None]
    hangupCause: NotRequired[str | None]
    sipStatus: NotRequired[int | None]
    faxSuccess: NotRequired[bool | None]
    faxResultCode: NotRequired[int | None]
    faxResultText: NotRequired[str | None]
    pagesTransferred: NotRequired[int | None]
    pagesTotal: NotRequired[int | None]
    transferRate: NotRequired[int | None]
    ecmUsed: NotRequired[bool | None]
    t38Used: NotRequired[bool | None]
    imageResolution: NotRequired[str | None]
    badRows: NotRequired[int | None]
    remoteStationId: NotRequired[str | None]


class FaxAttemptResource(TypedDict):
    type: Literal['fax-attempts']
    id: str
    attributes: NotRequired[FaxAttemptAttributes]
    links: NotRequired[ResourceLinks]


class FaxDocumentResponse(TypedDict):
    data: FaxResource
    included: NotRequired[list[FaxAttemptResource]]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class FaxCollectionDocument(TypedDict):
    data: list[FaxResource]
    included: NotRequired[list[FaxAttemptResource]]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes(TypedDict):
    read: NotRequired[bool]
    archived: NotRequired[bool]
    tags: NotRequired[Tags]


class Data(TypedDict):
    type: Literal['faxes']
    id: str
    attributes: NotRequired[Attributes]


class FaxUpdateRequest(TypedDict):
    data: Data


class CoverPageRequest(TypedDict):
    to_name: NotRequired[str]
    from_name: NotRequired[str]
    subject: NotRequired[str]
    message: NotRequired[str]


SendFaxMultipartRequest = TypedDict(
    'SendFaxMultipartRequest',
    {
        'fax_account': str,
        'to': str,
        'from': NotRequired[str],
        'resolution': NotRequired[FaxResolution],
        'cover_page': NotRequired[CoverPageRequest | None],
        'client_reference': NotRequired[str],
        'tags': NotRequired[Tags],
        'documents': list[bytes],
    },
)


SendFaxUrlRequest = TypedDict(
    'SendFaxUrlRequest',
    {
        'fax_account': str,
        'to': str,
        'from': NotRequired[str],
        'resolution': NotRequired[FaxResolution],
        'cover_page': NotRequired[CoverPageRequest | None],
        'client_reference': NotRequired[str],
        'tags': NotRequired[Tags],
        'documents': list[str],
    },
)


Data1 = TypedDict(
    'Data1',
    {
        'id': NotRequired[str],
        'status': NotRequired[FaxStatus],
        'direction': NotRequired[FaxDirection],
        'from': NotRequired[str | None],
        'to': NotRequired[str | None],
        'client_reference': NotRequired[str | None],
        'created_at': NotRequired[str | None],
    },
)


class SendFaxAccepted(TypedDict):
    data: Data1


class Data2(TypedDict):
    id: NotRequired[str]
    status: NotRequired[FaxStatus]


class CancelFaxResult(TypedDict):
    data: Data2


class MediaLink(TypedDict):
    url: str
    expires_at: str
    byte_size: int
    sha256: str


class FaxAccountAttributes(TypedDict):
    name: NotRequired[str]
    headerText: NotRequired[str | None]
    defaultFromE164: NotRequired[str | None]
    retentionDays: NotRequired[int]
    complianceRetention: NotRequired[bool]
    maxAttempts: NotRequired[int]
    status: NotRequired[FaxAccountStatus]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class FaxAccountRelationships(TypedDict):
    customer: NotRequired[RelationshipToOne]
    numbers: NotRequired[RelationshipToMany]


class FaxAccountResource(TypedDict):
    type: Literal['fax-accounts']
    id: str
    attributes: NotRequired[FaxAccountAttributes]
    relationships: NotRequired[FaxAccountRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class FaxAccountDocumentResponse(TypedDict):
    data: FaxAccountResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccountCollectionDocument(TypedDict):
    data: list[FaxAccountResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccountWritableAttributes(TypedDict):
    name: NotRequired[str]
    headerText: NotRequired[str | None]
    defaultFromE164: NotRequired[str | None]
    retentionDays: NotRequired[int]
    complianceRetention: NotRequired[bool]
    maxAttempts: NotRequired[int]
    status: NotRequired[FaxAccountStatus]


class Customer(TypedDict):
    data: ResourceIdentifier


class Relationships(TypedDict):
    customer: Customer


class Data3(TypedDict):
    type: Literal['fax-accounts']
    attributes: FaxAccountWritableAttributes
    relationships: Relationships


class FaxAccountCreateRequest(TypedDict):
    data: Data3


class Data4(TypedDict):
    type: Literal['fax-accounts']
    id: str
    attributes: FaxAccountWritableAttributes


class FaxAccountUpdateRequest(TypedDict):
    data: Data4


class FaxAccountUserAttributes(TypedDict):
    userEmail: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class Relationships1(TypedDict):
    faxAccount: NotRequired[RelationshipToOne]
    user: NotRequired[RelationshipToOne]


class FaxAccountUserResource(TypedDict):
    type: Literal['fax-account-users']
    id: str
    attributes: NotRequired[FaxAccountUserAttributes]
    relationships: NotRequired[Relationships1]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class FaxAccountUserDocumentResponse(TypedDict):
    data: FaxAccountUserResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccountUserCollectionDocument(TypedDict):
    data: list[FaxAccountUserResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccount(TypedDict):
    data: ResourceIdentifier


class User(TypedDict):
    data: ResourceIdentifier


class Relationships2(TypedDict):
    faxAccount: FaxAccount
    user: User


class Data5(TypedDict):
    type: Literal['fax-account-users']
    relationships: Relationships2


class FaxAccountUserCreateRequest(TypedDict):
    data: Data5


class Relationships3(TypedDict):
    customer: NotRequired[RelationshipToOne]
    routingTarget: NotRequired[RelationshipToOne]
    pbxNumber: NotRequired[RelationshipToOne]


class PhoneNumberMessaging(TypedDict):
    enabled: bool
    mmsEnabled: bool | None
    messageClass: Literal['A2P', 'P2P'] | None
    enabledAt: str | None


class WebhookEndpointAttributes(TypedDict):
    scopeType: NotRequired[WebhookScopeType]
    scopeId: NotRequired[str | None]
    url: NotRequired[str | None]
    events: NotRequired[list[WebhookEventType] | None]
    active: NotRequired[bool | None]
    secret: NotRequired[str | None]
    secretPreviousExpiresAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class WebhookEndpointResource(TypedDict):
    type: Literal['webhook-endpoints']
    id: str
    attributes: NotRequired[WebhookEndpointAttributes]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class WebhookEndpointDocumentResponse(TypedDict):
    data: WebhookEndpointResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class WebhookEndpointCollectionDocument(TypedDict):
    data: list[WebhookEndpointResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes2(TypedDict):
    url: str
    scopeType: WebhookScopeType
    scopeId: str
    events: NotRequired[list[WebhookEventType] | None]
    active: NotRequired[bool]


class Data6(TypedDict):
    type: Literal['webhook-endpoints']
    attributes: Attributes2


class WebhookEndpointCreateRequest(TypedDict):
    data: Data6


class Attributes3(TypedDict):
    url: str
    events: NotRequired[list[WebhookEventType] | None]
    active: NotRequired[bool]


class Data7(TypedDict):
    type: Literal['webhook-endpoints']
    id: str
    attributes: Attributes3


class WebhookEndpointUpdateRequest(TypedDict):
    data: Data7


class WebhookDeliveryAttributes(TypedDict):
    eventId: NotRequired[str | None]
    eventType: NotRequired[WebhookEventType]
    payloadSha256: NotRequired[str | None]
    status: NotRequired[WebhookDeliveryStatus]
    attemptNo: NotRequired[int | None]
    statusCode: NotRequired[int | None]
    durationMs: NotRequired[int | None]
    error: NotRequired[str | None]
    nextAttemptAt: NotRequired[str | None]
    deliveredAt: NotRequired[str | None]
    deadAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class Relationships4(TypedDict):
    endpoint: NotRequired[RelationshipToOne]


class WebhookDeliveryResource(TypedDict):
    type: Literal['webhook-deliveries']
    id: str
    attributes: NotRequired[WebhookDeliveryAttributes]
    relationships: NotRequired[Relationships4]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class WebhookDeliveryDocumentResponse(TypedDict):
    data: WebhookDeliveryResource
    included: NotRequired[list[WebhookEndpointResource]]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class WebhookDeliveryCollectionDocument(TypedDict):
    data: list[WebhookDeliveryResource]
    included: NotRequired[list[WebhookEndpointResource]]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


FaxEventData = TypedDict(
    'FaxEventData',
    {
        'id': NotRequired[str],
        'fax_account_id': NotRequired[str],
        'tenant_id': NotRequired[str],
        'customer_id': NotRequired[str | None],
        'direction': NotRequired[FaxDirection],
        'status': NotRequired[FaxStatus],
        'failure_code': NotRequired[FaxFailureCode],
        'from': NotRequired[str | None],
        'to': NotRequired[str | None],
        'region': NotRequired[str | None],
        'pages_total': NotRequired[int | None],
        'pages_transferred': NotRequired[int | None],
        'partial': NotRequired[bool | None],
        'attempt_count': NotRequired[int | None],
        'client_reference': NotRequired[str | None],
        'tags': NotRequired[Tags],
        'created_at': NotRequired[str | None],
        'completed_at': NotRequired[str | None],
    },
)


class FaxReceivedEventData(FaxEventData):
    render_failed: NotRequired[bool]


class WebhookEventEnvelope(TypedDict):
    event_id: str
    type: WebhookEventType
    occurred_at: str


class FaxEvent(WebhookEventEnvelope):
    data: FaxEventData


class FaxReceivedEvent(WebhookEventEnvelope):
    data: FaxReceivedEventData


class NumberLookupRequest(TypedDict, closed=True):
    number: str


NumberLookupDipStatus: TypeAlias = Literal['answered', 'no_data', 'failed']


class DialedNumberGeography(TypedDict):
    rateCenter: str | None
    state: str | None


class LrnFacts(TypedDict):
    lrn: str
    spid: str | None
    ocn: str | None
    lata: str | None
    lec: str | None
    lineType: str | None
    rateCenter: str | None
    state: str | None
    jurisdiction: str | None
    local: str | None
    portedAt: str | None


class CallerNameFacts(TypedDict):
    name: str


class MessagingFacts(TypedDict):
    enabled: bool
    provider: str | None
    country: str | None
    countryCode: str | None


class NumberLookupLrnComponent(TypedDict):
    status: NumberLookupDipStatus
    data: LrnFacts | None


class NumberLookupCallerNameComponent(TypedDict):
    status: NumberLookupDipStatus
    data: CallerNameFacts | None


class NumberLookupMessagingComponent(TypedDict):
    status: NumberLookupDipStatus
    data: MessagingFacts | None


class NumberLookupComponents(TypedDict):
    lrn: NumberLookupLrnComponent
    callerName: NumberLookupCallerNameComponent
    messaging: NumberLookupMessagingComponent


class NumberLookup(TypedDict):
    number: str
    lookedUpAt: str
    charged: bool
    dialedNumber: DialedNumberGeography
    components: NumberLookupComponents


class NumberLookupResult(TypedDict):
    data: NumberLookup


ProvisioningState: TypeAlias = Literal['pending', 'provisioning', 'active', 'failed']


ZtpVendor: TypeAlias = Literal['yealink']


MessagingEnablementStatus: TypeAlias = Literal[
    'scheduled', 'submitted', 'completed', 'failed'
]


MessagingEnablementFailureCause: TypeAlias = Literal[
    'provider_rejected', 'withdrawn', 'submission_error', 'poll_gave_up'
]


class MessagingEnablementAttributes(TypedDict):
    e164: NotRequired[str]
    status: NotRequired[MessagingEnablementStatus]
    stage: NotRequired[int]
    stageWord: NotRequired[str]
    detail: NotRequired[str | None]
    failedCause: NotRequired[MessagingEnablementFailureCause | None]
    scheduledFor: NotRequired[str | None]
    submittedAt: NotRequired[str | None]
    completedAt: NotRequired[str | None]
    failedAt: NotRequired[str | None]
    retryAllowedAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]


class MessagingEnablementRelationships(TypedDict):
    phoneNumber: NotRequired[RelationshipToOne]
    portOrder: NotRequired[RelationshipToOne]


InboundMessageKind: TypeAlias = Literal['sms', 'mms']


class InboundMessageMediaPart(TypedDict):
    content_type: NotRequired[str]
    filename: NotRequired[str | None]
    encoding: NotRequired[str]
    bytes: NotRequired[int]


InboundMessageAttributes = TypedDict(
    'InboundMessageAttributes',
    {
        'kind': NotRequired[InboundMessageKind],
        'from': NotRequired[str],
        'to': NotRequired[str],
        'body': NotRequired[str | None],
        'media': NotRequired[list[InboundMessageMediaPart]],
        'receivedAt': NotRequired[str],
        'createdAt': NotRequired[str],
        'updatedAt': NotRequired[str],
    },
)


class InboundMessageResource(TypedDict):
    type: Literal['inbound-messages']
    id: str
    attributes: NotRequired[InboundMessageAttributes]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class InboundMessageDocumentResponse(TypedDict):
    data: InboundMessageResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class InboundMessageCollectionDocument(TypedDict):
    data: list[InboundMessageResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class MessagingEnablementResource(TypedDict):
    type: Literal['messaging-enablements']
    id: str
    attributes: NotRequired[MessagingEnablementAttributes]
    relationships: NotRequired[MessagingEnablementRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class MessagingEnablementDocumentResponse(TypedDict):
    data: MessagingEnablementResource
    included: NotRequired[list[dict[str, Any]]]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class MessagingEnablementCollectionDocument(TypedDict):
    data: list[MessagingEnablementResource]
    included: NotRequired[list[dict[str, Any]]]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class PhoneNumber(TypedDict):
    data: ResourceIdentifier


class Relationships5(TypedDict):
    phoneNumber: PhoneNumber


class Data8(TypedDict):
    type: Literal['messaging-enablements']
    relationships: Relationships5


class MessagingEnablementCreateRequest(TypedDict):
    data: Data8


class ZtpDeviceAttributes(TypedDict):
    mac: NotRequired[str]
    vendor: NotRequired[ZtpVendor]
    label: NotRequired[str | None]
    state: NotRequired[ProvisioningState]
    stateDetail: NotRequired[str | None]
    stateChangedAt: NotRequired[str | None]
    registeredAt: NotRequired[str | None]
    lastConnectedAt: NotRequired[str | None]
    lastIp: NotRequired[str | None]
    observedAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class ZtpDeviceRelationships(TypedDict):
    customer: NotRequired[RelationshipToOne]


class ZtpDeviceResource(TypedDict):
    type: Literal['ztp-devices']
    id: str
    attributes: NotRequired[ZtpDeviceAttributes]
    relationships: NotRequired[ZtpDeviceRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class ZtpDeviceDocumentResponse(TypedDict):
    data: ZtpDeviceResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class ZtpDeviceCollectionDocument(TypedDict):
    data: list[ZtpDeviceResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes4(TypedDict):
    mac: str
    label: NotRequired[str | None]


class Customer1(TypedDict):
    data: ResourceIdentifier | None


class Relationships6(TypedDict):
    customer: NotRequired[Customer1]


class Data9(TypedDict):
    type: Literal['ztp-devices']
    attributes: Attributes4
    relationships: NotRequired[Relationships6]


class ZtpDeviceCreateRequest(TypedDict):
    data: Data9


class Attributes5(TypedDict):
    label: NotRequired[str | None]


class Relationships7(TypedDict):
    customer: NotRequired[Customer1]


class Data10(TypedDict):
    type: Literal['ztp-devices']
    id: str
    attributes: NotRequired[Attributes5]
    relationships: NotRequired[Relationships7]


class ZtpDeviceUpdateRequest(TypedDict):
    data: Data10


PortOrderStatus: TypeAlias = Literal[
    'draft',
    'awaiting_signature',
    'awaiting_review',
    'submitted',
    'foc_assigned',
    'completed',
    'failed',
]


PortNumberFailureCause: TypeAlias = Literal['withdrawn', 'carrier_refused'] | None


PortDocumentKind: TypeAlias = Literal['loa', 'bill']


PortType: TypeAlias = Literal['full', 'partial'] | None


PortNumberType: TypeAlias = Literal['landline', 'wireless', 'voip'] | None


PortOrderTaskBillState: TypeAlias = Literal['missing', 'received']


PortOrderTaskDateState: TypeAlias = Literal['missing', 'chosen']


PortOrderTaskSignatureState: TypeAlias = Literal['not_ready', 'ready', 'signed']


PortOrderBillExtractionStatus: TypeAlias = Literal[
    'pending', 'done', 'failed', 'skipped'
]


PortOrderRequestLinkMailKind: TypeAlias = Literal['bill', 'signature']


class PortOrderNumberState(TypedDict):
    e164: NotRequired[str | None]
    status: NotRequired[PortOrderStatus]
    cause: NotRequired[PortNumberFailureCause]
    focDate: NotRequired[str | None]
    stopped: NotRequired[bool]
    stoppedSince: NotRequired[str | None]


class PortOrderDocumentSlot(TypedDict):
    sha256: NotRequired[str]
    uploadedAt: NotRequired[str | None]


class PortOrderDocuments(TypedDict):
    loa: NotRequired[PortOrderDocumentSlot | None]
    bill: NotRequired[PortOrderDocumentSlot | None]


class PortOrderUnsignedLoa(TypedDict):
    sha256: NotRequired[str]
    generatedAt: NotRequired[str | None]


class PortOrderRequestLinkState(TypedDict):
    active: NotRequired[bool]


class PortOrderTasks(TypedDict):
    bill: NotRequired[PortOrderTaskBillState]
    date: NotRequired[PortOrderTaskDateState]
    signature: NotRequired[PortOrderTaskSignatureState]


class PortOrderBillExtraction(TypedDict):
    status: NotRequired[PortOrderBillExtractionStatus]
    fields: NotRequired[list[str]]
    extractedAt: NotRequired[str | None]


class PortOrderAttributes(TypedDict):
    label: NotRequired[str]
    country: NotRequired[str]
    status: NotRequired[PortOrderStatus]
    endUserName: NotRequired[str | None]
    endUserAddress: NotRequired[str | None]
    loaSigner: NotRequired[str | None]
    loaDate: NotRequired[str | None]
    currentProvider: NotRequired[str | None]
    accountNumber: NotRequired[str | None]
    monthlyMou: NotRequired[int]
    accountPin: NotRequired[None]
    accountPinAttestedNone: NotRequired[bool]
    billingPhone: NotRequired[str | None]
    portType: NotRequired[PortType]
    newBillingNumber: NotRequired[str | None]
    serviceStreetNumber: NotRequired[str | None]
    serviceStreetName: NotRequired[str | None]
    serviceCity: NotRequired[str | None]
    serviceState: NotRequired[str | None]
    serviceZip: NotRequired[str | None]
    requestedFocDate: NotRequired[str | None]
    contactName: NotRequired[str | None]
    contactTitle: NotRequired[str | None]
    contactEmail: NotRequired[str | None]
    contactPhone: NotRequired[str | None]
    numbersNotTransferring: NotRequired[str | None]
    numbers: NotRequired[list[str]]
    correctionsRequired: NotRequired[bool]
    correctionsNote: NotRequired[str | None]
    numberStates: NotRequired[list[PortOrderNumberState]]
    documents: NotRequired[PortOrderDocuments]
    unsignedLoa: NotRequired[PortOrderUnsignedLoa | None]
    requestLink: NotRequired[PortOrderRequestLinkState]
    tasks: NotRequired[PortOrderTasks]
    detailsConfirmedAt: NotRequired[str | None]
    signatureRequestedAt: NotRequired[str | None]
    billExtraction: NotRequired[PortOrderBillExtraction | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class PortOrderResource(TypedDict):
    type: Literal['port-orders']
    id: str
    attributes: NotRequired[PortOrderAttributes]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class PortOrderDocumentResponse(TypedDict):
    data: PortOrderResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class PortOrderCollectionDocument(TypedDict):
    data: list[PortOrderResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes6(TypedDict):
    label: str
    country: NotRequired[str]


class Data11(TypedDict):
    type: Literal['port-orders']
    attributes: Attributes6


class PortOrderCreateRequest(TypedDict):
    data: Data11


class PortOrderNumberInput1(TypedDict):
    e164: str
    numberType: NotRequired[PortNumberType]


PortOrderNumberInput: TypeAlias = str | PortOrderNumberInput1


class Attributes7(TypedDict):
    label: NotRequired[str | None]
    endUserName: NotRequired[str | None]
    endUserAddress: NotRequired[str | None]
    loaSigner: NotRequired[str | None]
    loaDate: NotRequired[str | None]
    currentProvider: NotRequired[str | None]
    accountNumber: NotRequired[str | None]
    monthlyMou: NotRequired[int | None]
    accountPin: NotRequired[str | None]
    accountPinAttestedNone: NotRequired[bool]
    billingPhone: NotRequired[str | None]
    portType: NotRequired[PortType]
    newBillingNumber: NotRequired[str | None]
    serviceStreetNumber: NotRequired[str | None]
    serviceStreetName: NotRequired[str | None]
    serviceCity: NotRequired[str | None]
    serviceState: NotRequired[str | None]
    serviceZip: NotRequired[str | None]
    requestedFocDate: NotRequired[str | None]
    contactName: NotRequired[str | None]
    contactTitle: NotRequired[str | None]
    contactEmail: NotRequired[str | None]
    contactPhone: NotRequired[str | None]
    numbersNotTransferring: NotRequired[str | None]
    numbers: NotRequired[list[PortOrderNumberInput] | None]


class Data12(TypedDict):
    type: Literal['port-orders']
    id: str
    attributes: NotRequired[Attributes7]


class PortOrderUpdateRequest(TypedDict):
    data: Data12


class PortOrderDocumentUploadRequest(TypedDict):
    kind: PortDocumentKind
    file: bytes


class Data13(TypedDict):
    id: NotRequired[str]
    status: NotRequired[PortOrderStatus]
    numbers: NotRequired[list[str]]


class PortOrderSubmitted(TypedDict):
    data: Data13


class Data14(TypedDict):
    id: NotRequired[str]
    kind: NotRequired[PortDocumentKind]
    sha256: NotRequired[str | None]


class PortOrderDocumentStored(TypedDict):
    data: Data14


class Data15(TypedDict):
    id: NotRequired[str]
    sha256: NotRequired[str | None]


class PortOrderLoaGenerated(TypedDict):
    data: Data15


class Data16(TypedDict):
    id: NotRequired[str]
    url: NotRequired[str]


class PortOrderRequestLinkIssued(TypedDict):
    data: Data16


class Data17(TypedDict):
    id: NotRequired[str]
    revoked: NotRequired[bool]


class PortOrderRequestLinkRevoked(TypedDict):
    data: Data17


class PortOrderRequestLinkSendRequest(TypedDict):
    to: str
    kind: NotRequired[PortOrderRequestLinkMailKind]
    note: NotRequired[str | None]


class Data18(TypedDict):
    id: NotRequired[str]
    sent_to: NotRequired[str]


class PortOrderRequestLinkSent(TypedDict):
    data: Data18


class Error(TypedDict):
    status: str
    title: NotRequired[str]
    detail: NotRequired[str]
    code: NotRequired[ErrorCode]
    source: NotRequired[ErrorSource]
    meta: NotRequired[dict[str, Any]]


class ErrorDocument(TypedDict):
    errors: list[Error]


class Attributes1(TypedDict):
    e164: NotRequired[str | None]
    status: NotRequired[Literal['pending', 'active', 'failed', 'releasing'] | None]
    country: NotRequired[str | None]
    activatedAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    messaging: NotRequired[PhoneNumberMessaging]


class PhoneNumberResource(TypedDict):
    type: Literal['phone-numbers']
    id: str
    attributes: NotRequired[Attributes1]
    relationships: NotRequired[Relationships3]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class PhoneNumberCollectionDocument(TypedDict):
    data: list[PhoneNumberResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]
