"""The vendored spec's schemas, as types. Machine-written — do not edit.

Each `TypedDict` below describes one JSON shape from spec/openapi.yaml, and
describes it at TYPE-CHECK TIME ONLY: a `TypedDict` is a plain `dict` at
runtime, so this module defines no behaviour and constructs nothing. It is
not imported by `ringivo/__init__.py`, so it costs an ordinary caller
nothing.

Nothing generated crosses the public boundary — `models.py` owns the frozen
objects this client hands back, and it reads the wire defensively rather
than trusting these shapes. What these types are FOR is reading: they are
the machine-checked record of what the API sends and accepts, for anyone
reaching past the wrapped surface with `Ringivo.request()`.

Regenerate with scripts/generate.sh, which overwrites this file whole.
"""
from __future__ import annotations

#
# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   version:   0.74.0

from typing import Any, Literal, TypeAlias

from typing_extensions import NotRequired, TypedDict


class OauthTokenRequest(TypedDict):
    grant_type: Literal['client_credentials']
    client_id: NotRequired[str]
    client_secret: NotRequired[str]
    tenant: str
    customer: NotRequired[str | None]
    scope: str


class OauthTokenResponse(TypedDict):
    access_token: str
    token_type: str
    expires_in: int
    scope: NotRequired[str]
    scopes: list[str]


class OauthError(TypedDict):
    error: str
    error_description: str
    hint: NotRequired[str]


class ResourceIdentifier(TypedDict):
    type: str
    id: str


class ResourceLinks(TypedDict):
    self: NotRequired[str]


class CollectionLinks(TypedDict):
    self: NotRequired[str | None]
    first: NotRequired[str]
    prev: NotRequired[str]
    next: NotRequired[str]


class PageMeta(TypedDict):
    size: int
    nextCursor: str | None
    total: NotRequired[int]


class DocumentMeta(TypedDict):
    page: NotRequired[PageMeta]


class Page(TypedDict):
    cursor: NotRequired[str]


class ResourceMeta(TypedDict):
    page: NotRequired[Page]


class RelationshipToOne(TypedDict):
    links: NotRequired[ResourceLinks]
    data: NotRequired[ResourceIdentifier | None]


class RelationshipToMany(TypedDict):
    links: NotRequired[ResourceLinks]
    data: NotRequired[list[ResourceIdentifier]]


class ErrorSource(TypedDict):
    pointer: NotRequired[str]
    parameter: NotRequired[str]


ErrorCode: TypeAlias = Literal[
    'validation_failed',
    'caller_id_not_permitted',
    'document_too_large',
    'too_many_pages',
    'unsupported_media_type',
    'fax_account_suspended',
    'fax_account_has_routed_numbers',
    'number_is_default_caller_id',
    'rate_limited',
    'not_found',
    'forbidden',
    'internal_error',
    'sip_trunk_refused',
    'transcript_pending',
    'transcript_failed',
]


FaxDirection: TypeAlias = Literal['inbound', 'outbound']


FaxStatus: TypeAlias = Literal[
    'queued',
    'converting',
    'sending',
    'delivered',
    'partial',
    'cancelled',
    'received',
    'failed',
]


FaxFailureCode: TypeAlias = (
    Literal[
        'busy',
        'no_answer',
        'no_fax_tone',
        'negotiation_failed',
        'line_quality',
        'line_dropped',
        'incompatible',
        'document_error',
        'invalid_number',
        'carrier_rejected',
        'internal_error',
    ]
    | None
)


FaxAccountStatus: TypeAlias = Literal['active', 'suspended']


FaxResolution: TypeAlias = Literal['fine', 'standard']


WebhookScopeType: TypeAlias = Literal['tenant', 'customer']


WebhookEventType: TypeAlias = Literal[
    'fax.received',
    'fax.queued',
    'fax.converting',
    'fax.sending',
    'fax.delivered',
    'fax.partial',
    'fax.failed',
    'fax.cancelled',
    'message.received',
    'port_order.bill_extraction_settled',
    'port_order.status_changed',
    'pbx_change.confirmed',
    'pbx_change.stalled',
    'call-recording.available',
    'call-transcript.available',
    'webhook.heartbeat',
]


WebhookDeliveryStatus: TypeAlias = Literal['pending', 'dead']


Tags: TypeAlias = dict[str, Any] | None


CoverPage: TypeAlias = dict[str, Any] | None


class FaxDocumentMetadata(TypedDict):
    kind: NotRequired[Literal['source', 'tiff', 'pdf', 'thumb']]
    ordinal: NotRequired[int]
    contentType: NotRequired[str | None]
    byteSize: NotRequired[int | None]
    sha256: NotRequired[str | None]
    pages: NotRequired[int | None]


FaxAttributes = TypedDict(
    'FaxAttributes',
    {
        'direction': NotRequired[FaxDirection],
        'status': NotRequired[FaxStatus],
        'failureCode': NotRequired[FaxFailureCode],
        'from': NotRequired[str | None],
        'to': NotRequired[str | None],
        'pagesTotal': NotRequired[int | None],
        'pagesTransferred': NotRequired[int | None],
        'partial': NotRequired[bool | None],
        'attemptCount': NotRequired[int | None],
        'resolution': NotRequired[str | None],
        'clientReference': NotRequired[str | None],
        'coverPage': NotRequired[CoverPage],
        'read': NotRequired[bool],
        'archived': NotRequired[bool],
        'tags': NotRequired[Tags],
        'documents': NotRequired[list[FaxDocumentMetadata]],
        'createdAt': NotRequired[str | None],
        'completedAt': NotRequired[str | None],
    },
)


class FaxRelationships(TypedDict):
    faxAccount: NotRequired[RelationshipToOne]
    attempts: NotRequired[RelationshipToMany]


class FaxResource(TypedDict):
    type: Literal['faxes']
    id: str
    attributes: NotRequired[FaxAttributes]
    relationships: NotRequired[FaxRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class FaxAttemptAttributes(TypedDict):
    attemptNo: NotRequired[int | None]
    transportProfile: NotRequired[dict[str, Any] | None]
    startedAt: NotRequired[str | None]
    answeredAt: NotRequired[str | None]
    endedAt: NotRequired[str | None]
    billableMs: NotRequired[int | None]
    hangupCause: NotRequired[str | None]
    sipStatus: NotRequired[int | None]
    faxSuccess: NotRequired[bool | None]
    faxResultCode: NotRequired[int | None]
    faxResultText: NotRequired[str | None]
    pagesTransferred: NotRequired[int | None]
    pagesTotal: NotRequired[int | None]
    transferRate: NotRequired[int | None]
    ecmUsed: NotRequired[bool | None]
    t38Used: NotRequired[bool | None]
    imageResolution: NotRequired[str | None]
    badRows: NotRequired[int | None]
    remoteStationId: NotRequired[str | None]


class FaxAttemptResource(TypedDict):
    type: Literal['fax-attempts']
    id: str
    attributes: NotRequired[FaxAttemptAttributes]
    links: NotRequired[ResourceLinks]


class FaxDocumentResponse(TypedDict):
    data: FaxResource
    included: NotRequired[list[FaxAttemptResource]]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class FaxCollectionDocument(TypedDict):
    data: list[FaxResource]
    included: NotRequired[list[FaxAttemptResource]]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes(TypedDict):
    read: NotRequired[bool]
    archived: NotRequired[bool]
    tags: NotRequired[Tags]


class Data(TypedDict):
    type: Literal['faxes']
    id: str
    attributes: NotRequired[Attributes]


class FaxUpdateRequest(TypedDict):
    data: Data


class CoverPageRequest(TypedDict):
    to_name: NotRequired[str]
    from_name: NotRequired[str]
    subject: NotRequired[str]
    message: NotRequired[str]


SendFaxMultipartRequest = TypedDict(
    'SendFaxMultipartRequest',
    {
        'fax_account': str,
        'to': str,
        'from': NotRequired[str],
        'resolution': NotRequired[FaxResolution],
        'cover_page': NotRequired[CoverPageRequest | None],
        'client_reference': NotRequired[str],
        'tags': NotRequired[Tags],
        'documents': list[bytes],
    },
)


SendFaxUrlRequest = TypedDict(
    'SendFaxUrlRequest',
    {
        'fax_account': str,
        'to': str,
        'from': NotRequired[str],
        'resolution': NotRequired[FaxResolution],
        'cover_page': NotRequired[CoverPageRequest | None],
        'client_reference': NotRequired[str],
        'tags': NotRequired[Tags],
        'documents': list[str],
    },
)


Data1 = TypedDict(
    'Data1',
    {
        'id': NotRequired[str],
        'status': NotRequired[FaxStatus],
        'direction': NotRequired[FaxDirection],
        'from': NotRequired[str | None],
        'to': NotRequired[str | None],
        'client_reference': NotRequired[str | None],
        'created_at': NotRequired[str | None],
    },
)


class SendFaxAccepted(TypedDict):
    data: Data1


class Data2(TypedDict):
    id: NotRequired[str]
    status: NotRequired[FaxStatus]


class CancelFaxResult(TypedDict):
    data: Data2


class MediaLink(TypedDict):
    url: str
    expires_at: str
    byte_size: int
    sha256: str


class FaxAccountAttributes(TypedDict):
    name: NotRequired[str]
    headerText: NotRequired[str | None]
    headerTemplate: NotRequired[str | None]
    headerTimezone: NotRequired[str | None]
    defaultFromE164: NotRequired[str | None]
    retentionDays: NotRequired[int | None]
    retentionPages: NotRequired[int | None]
    status: NotRequired[FaxAccountStatus]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class Customer(TypedDict):
    data: ResourceIdentifier


class FaxAccountRelationships(TypedDict):
    customer: NotRequired[Customer]
    numbers: NotRequired[RelationshipToMany]


class FaxAccountResource(TypedDict):
    type: Literal['fax-accounts']
    id: str
    attributes: NotRequired[FaxAccountAttributes]
    relationships: NotRequired[FaxAccountRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class FaxAccountDocumentResponse(TypedDict):
    data: FaxAccountResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccountCollectionDocument(TypedDict):
    data: list[FaxAccountResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccountWritableAttributes(TypedDict):
    name: NotRequired[str]
    headerText: NotRequired[str | None]
    headerTemplate: NotRequired[str | None]
    headerTimezone: NotRequired[str | None]
    defaultFromE164: NotRequired[str | None]
    retentionDays: NotRequired[int | None]
    retentionPages: NotRequired[int | None]
    status: NotRequired[FaxAccountStatus]


class FaxAccountCreateAttributes(TypedDict):
    name: str
    headerText: NotRequired[str | None]
    headerTemplate: NotRequired[str | None]
    headerTimezone: NotRequired[str | None]
    defaultFromE164: NotRequired[str | None]
    retentionDays: NotRequired[int | None]
    retentionPages: NotRequired[int | None]
    status: NotRequired[FaxAccountStatus]


class Relationships(TypedDict):
    customer: Customer


class Data3(TypedDict):
    type: Literal['fax-accounts']
    attributes: FaxAccountCreateAttributes
    relationships: Relationships


class FaxAccountCreateRequest(TypedDict):
    data: Data3


class Data4(TypedDict):
    type: Literal['fax-accounts']
    id: str
    attributes: FaxAccountWritableAttributes


class FaxAccountUpdateRequest(TypedDict):
    data: Data4


class FaxAccountUserAttributes(TypedDict):
    userEmail: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class FaxAccount(TypedDict):
    data: ResourceIdentifier


class User(TypedDict):
    data: ResourceIdentifier


class Relationships1(TypedDict):
    faxAccount: NotRequired[FaxAccount]
    user: NotRequired[User]


class FaxAccountUserResource(TypedDict):
    type: Literal['fax-account-users']
    id: str
    attributes: NotRequired[FaxAccountUserAttributes]
    relationships: NotRequired[Relationships1]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class FaxAccountUserDocumentResponse(TypedDict):
    data: FaxAccountUserResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccountUserCollectionDocument(TypedDict):
    data: list[FaxAccountUserResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Relationships2(TypedDict):
    faxAccount: FaxAccount
    user: User


class Data5(TypedDict):
    type: Literal['fax-account-users']
    relationships: Relationships2


class FaxAccountUserCreateRequest(TypedDict):
    data: Data5


class Relationships3(TypedDict):
    customer: NotRequired[RelationshipToOne]
    routingTarget: NotRequired[RelationshipToOne]
    pbxNumber: NotRequired[RelationshipToOne]


class PhoneNumberMessaging(TypedDict):
    enabled: bool
    mmsEnabled: bool | None
    messageClass: Literal['A2P', 'P2P'] | None
    enabledAt: str | None


class PhoneNumberVoice(TypedDict):
    enabled: bool


class PhoneNumberAssignRequest(TypedDict):
    customer_id: str


class PhoneNumberRouteRequest(TypedDict):
    target_type: NotRequired[Literal['pbx', 'fax', 'sip_trunk']]
    fax_account: NotRequired[str]
    sip_trunk: NotRequired[str]


class WebhookEndpointAttributes(TypedDict):
    scopeType: NotRequired[WebhookScopeType]
    scopeId: NotRequired[str | None]
    url: NotRequired[str | None]
    events: NotRequired[list[WebhookEventType] | None]
    filter: NotRequired[str | None]
    active: NotRequired[bool | None]
    secret: NotRequired[str | None]
    secretPreviousExpiresAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class WebhookEndpointResource(TypedDict):
    type: Literal['webhook-endpoints']
    id: str
    attributes: NotRequired[WebhookEndpointAttributes]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class WebhookEndpointDocumentResponse(TypedDict):
    data: WebhookEndpointResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class WebhookEndpointCollectionDocument(TypedDict):
    data: list[WebhookEndpointResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes2(TypedDict):
    url: str
    scopeType: WebhookScopeType
    scopeId: str
    events: list[WebhookEventType]
    filter: NotRequired[str | None]
    active: NotRequired[bool]


class Data6(TypedDict):
    type: Literal['webhook-endpoints']
    attributes: Attributes2


class WebhookEndpointCreateRequest(TypedDict):
    data: Data6


class Attributes3(TypedDict):
    url: NotRequired[str]
    events: NotRequired[list[WebhookEventType]]
    filter: NotRequired[str | None]
    active: NotRequired[bool]
    scopeType: NotRequired[WebhookScopeType]
    scopeId: NotRequired[str]


class Data7(TypedDict):
    type: Literal['webhook-endpoints']
    id: str
    attributes: Attributes3


class WebhookEndpointUpdateRequest(TypedDict):
    data: Data7


class WebhookDeliveryAttributes(TypedDict):
    eventId: NotRequired[str | None]
    eventType: NotRequired[WebhookEventType]
    payloadSha256: NotRequired[str | None]
    status: NotRequired[WebhookDeliveryStatus]
    attemptNo: NotRequired[int | None]
    statusCode: NotRequired[int | None]
    durationMs: NotRequired[int | None]
    error: NotRequired[str | None]
    nextAttemptAt: NotRequired[str | None]
    deliveredAt: NotRequired[str | None]
    deadAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class Relationships4(TypedDict):
    endpoint: NotRequired[RelationshipToOne]


class WebhookDeliveryResource(TypedDict):
    type: Literal['webhook-deliveries']
    id: str
    attributes: NotRequired[WebhookDeliveryAttributes]
    relationships: NotRequired[Relationships4]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class WebhookDeliveryDocumentResponse(TypedDict):
    data: WebhookDeliveryResource
    included: NotRequired[list[WebhookEndpointResource]]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class WebhookDeliveryCollectionDocument(TypedDict):
    data: list[WebhookDeliveryResource]
    included: NotRequired[list[WebhookEndpointResource]]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


FaxEventData = TypedDict(
    'FaxEventData',
    {
        'id': NotRequired[str],
        'fax_account_id': NotRequired[str],
        'tenant_id': NotRequired[str],
        'customer_id': NotRequired[str | None],
        'direction': NotRequired[FaxDirection],
        'status': NotRequired[FaxStatus],
        'failure_code': NotRequired[FaxFailureCode],
        'from': NotRequired[str | None],
        'to': NotRequired[str | None],
        'region': NotRequired[str | None],
        'pages_total': NotRequired[int | None],
        'pages_transferred': NotRequired[int | None],
        'partial': NotRequired[bool | None],
        'attempt_count': NotRequired[int | None],
        'client_reference': NotRequired[str | None],
        'tags': NotRequired[Tags],
        'created_at': NotRequired[str | None],
        'completed_at': NotRequired[str | None],
    },
)


class FaxReceivedEventData(FaxEventData):
    render_failed: NotRequired[bool]


class WebhookEventEnvelope(TypedDict):
    event_id: str
    type: WebhookEventType
    occurred_at: str


class FaxEvent(WebhookEventEnvelope):
    data: FaxEventData


class FaxReceivedEvent(WebhookEventEnvelope):
    data: FaxReceivedEventData


class CallRecordingAvailableEventData(TypedDict):
    id: NotRequired[str]
    customer_id: NotRequired[str | None]
    call_id: NotRequired[str]
    ccc_id: NotRequired[str]
    duration_seconds: NotRequired[int | None]
    byte_size: NotRequired[int]
    sha256: NotRequired[str]
    superseded: NotRequired[bool]
    recorded_at: NotRequired[str | None]
    ended_at: NotRequired[str | None]


class CallRecordingAvailableEvent(WebhookEventEnvelope):
    data: CallRecordingAvailableEventData


class CallTranscriptAvailableEventData(TypedDict):
    id: NotRequired[str]
    recording_id: NotRequired[str]
    customer_id: NotRequired[str | None]
    call_id: NotRequired[str]
    ccc_id: NotRequired[str]
    language: NotRequired[str]
    duration_seconds: NotRequired[int | None]


class WebhookHeartbeatEventData(TypedDict):
    region: NotRequired[str]
    emitted_at: NotRequired[str]
    sequence: NotRequired[int]
    nonce: NotRequired[str]
    origin: NotRequired[Literal['scheduler', 'api']]


class WebhookHeartbeatEvent(WebhookEventEnvelope):
    data: WebhookHeartbeatEventData


class CallTranscriptAvailableEvent(WebhookEventEnvelope):
    data: CallTranscriptAvailableEventData


class PbxChangeEventData(TypedDict):
    intent_id: NotRequired[str]
    tenant_id: NotRequired[str]
    target_id: NotRequired[str]
    table: NotRequired[str]
    fields: NotRequired[list[str]]
    submitted_at: NotRequired[str]


class PbxChangeConfirmedEvent(WebhookEventEnvelope):
    data: PbxChangeEventData


class PbxChangeStalledEvent(WebhookEventEnvelope):
    data: PbxChangeEventData


class NumberLookupRequest(TypedDict, closed=True):
    number: str


NumberLookupDipStatus: TypeAlias = Literal['answered', 'no_data', 'failed']


class DialedNumberGeography(TypedDict):
    rateCenter: str | None
    state: str | None


class LrnFacts(TypedDict):
    lrn: str
    spid: str | None
    ocn: str | None
    lata: str | None
    lec: str | None
    lineType: str | None
    rateCenter: str | None
    state: str | None
    jurisdiction: str | None
    local: str | None
    portedAt: str | None


class CallerNameFacts(TypedDict):
    name: str


class MessagingFacts(TypedDict):
    enabled: bool
    provider: str | None
    country: str | None
    countryCode: str | None


class NumberLookupLrnComponent(TypedDict):
    status: NumberLookupDipStatus
    data: LrnFacts | None


class NumberLookupCallerNameComponent(TypedDict):
    status: NumberLookupDipStatus
    data: CallerNameFacts | None


class NumberLookupMessagingComponent(TypedDict):
    status: NumberLookupDipStatus
    data: MessagingFacts | None


class NumberLookupComponents(TypedDict):
    lrn: NumberLookupLrnComponent
    callerName: NumberLookupCallerNameComponent
    messaging: NumberLookupMessagingComponent


class NumberLookup(TypedDict):
    number: str
    lookedUpAt: str
    charged: bool
    dialedNumber: DialedNumberGeography
    components: NumberLookupComponents


class NumberLookupResult(TypedDict):
    data: NumberLookup


ProvisioningState: TypeAlias = Literal['pending', 'provisioning', 'active', 'failed']


ZtpVendor: TypeAlias = Literal['yealink']


MessagingEnablementStatus: TypeAlias = Literal[
    'awaiting_signature', 'scheduled', 'submitted', 'completed', 'failed'
]


MessagingEnablementFailureCause: TypeAlias = Literal[
    'provider_rejected', 'withdrawn', 'submission_error', 'poll_gave_up'
]


class MessagingEnablementAttributes(TypedDict):
    e164: NotRequired[str]
    status: NotRequired[MessagingEnablementStatus]
    stage: NotRequired[int]
    stageWord: NotRequired[str]
    detail: NotRequired[str | None]
    failedCause: NotRequired[MessagingEnablementFailureCause | None]
    scheduledFor: NotRequired[str | None]
    submittedAt: NotRequired[str | None]
    completedAt: NotRequired[str | None]
    failedAt: NotRequired[str | None]
    retryAllowedAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]


class MessagingEnablementRelationships(TypedDict):
    phoneNumber: NotRequired[RelationshipToOne]
    portOrder: NotRequired[RelationshipToOne]


InboundMessageKind: TypeAlias = Literal['sms', 'mms']


class InboundMessageMediaPart(TypedDict):
    content_type: NotRequired[str]
    filename: NotRequired[str | None]
    encoding: NotRequired[str]
    bytes: NotRequired[int]


InboundMessageAttributes = TypedDict(
    'InboundMessageAttributes',
    {
        'kind': NotRequired[InboundMessageKind],
        'from': NotRequired[str],
        'to': NotRequired[str],
        'body': NotRequired[str | None],
        'media': NotRequired[list[InboundMessageMediaPart]],
        'receivedAt': NotRequired[str],
        'createdAt': NotRequired[str],
        'updatedAt': NotRequired[str],
    },
)


class InboundMessageResource(TypedDict):
    type: Literal['inbound-messages']
    id: str
    attributes: NotRequired[InboundMessageAttributes]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class InboundMessageDocumentResponse(TypedDict):
    data: InboundMessageResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class InboundMessageCollectionDocument(TypedDict):
    data: list[InboundMessageResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class MessagingEnablementResource(TypedDict):
    type: Literal['messaging-enablements']
    id: str
    attributes: NotRequired[MessagingEnablementAttributes]
    relationships: NotRequired[MessagingEnablementRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class MessagingEnablementDocumentResponse(TypedDict):
    data: MessagingEnablementResource
    included: NotRequired[list[dict[str, Any]]]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class MessagingEnablementCollectionDocument(TypedDict):
    data: list[MessagingEnablementResource]
    included: NotRequired[list[dict[str, Any]]]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class PhoneNumber(TypedDict):
    data: ResourceIdentifier


class Relationships5(TypedDict):
    phoneNumber: PhoneNumber


class Data8(TypedDict):
    type: Literal['messaging-enablements']
    relationships: Relationships5


class MessagingEnablementCreateRequest(TypedDict):
    data: Data8


HostedMessagingOrderStatus: TypeAlias = Literal[
    'claimed', 'awaiting_signature', 'submitted', 'failed'
]


HostedMessagingMechanism: TypeAlias = Literal['claimed', 'enabled']


class HostedMessagingOrderAttributes(TypedDict):
    e164: NotRequired[str]
    status: NotRequired[HostedMessagingOrderStatus]
    mechanism: NotRequired[HostedMessagingMechanism]
    createdAt: NotRequired[str | None]


class HostedMessagingOrderRelationships(TypedDict):
    phoneNumber: NotRequired[RelationshipToOne]
    messagingEnablement: NotRequired[RelationshipToOne]
    customer: NotRequired[RelationshipToOne]


class HostedMessagingOrderResource(TypedDict):
    type: Literal['hosted-messaging-orders']
    id: str
    attributes: NotRequired[HostedMessagingOrderAttributes]
    relationships: NotRequired[HostedMessagingOrderRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class HostedMessagingOrderDocumentResponse(TypedDict):
    data: HostedMessagingOrderResource
    included: NotRequired[list[dict[str, Any]]]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class HostedMessagingOrderCollectionDocument(TypedDict):
    data: list[HostedMessagingOrderResource]
    included: NotRequired[list[dict[str, Any]]]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class EndUser(TypedDict):
    name: str
    email: str


class Attributes4(TypedDict):
    e164: str
    endUser: EndUser


class Relationships6(TypedDict):
    customer: NotRequired[Customer]


class Data9(TypedDict):
    type: Literal['hosted-messaging-orders']
    attributes: Attributes4
    relationships: NotRequired[Relationships6]


class HostedMessagingOrderCreateRequest(TypedDict):
    data: Data9


class ZtpDeviceAttributes(TypedDict):
    mac: NotRequired[str]
    vendor: NotRequired[ZtpVendor]
    label: NotRequired[str | None]
    state: NotRequired[ProvisioningState]
    stateDetail: NotRequired[str | None]
    stateChangedAt: NotRequired[str | None]
    registeredAt: NotRequired[str | None]
    lastConnectedAt: NotRequired[str | None]
    lastIp: NotRequired[str | None]
    observedAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class ZtpDeviceRelationships(TypedDict):
    customer: NotRequired[RelationshipToOne]


class ZtpDeviceResource(TypedDict):
    type: Literal['ztp-devices']
    id: str
    attributes: NotRequired[ZtpDeviceAttributes]
    relationships: NotRequired[ZtpDeviceRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class ZtpDeviceDocumentResponse(TypedDict):
    data: ZtpDeviceResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class ZtpDeviceCollectionDocument(TypedDict):
    data: list[ZtpDeviceResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes5(TypedDict):
    mac: str
    label: NotRequired[str | None]


class Customer3(TypedDict):
    data: ResourceIdentifier | None


class Relationships7(TypedDict):
    customer: NotRequired[Customer3]


class Data10(TypedDict):
    type: Literal['ztp-devices']
    attributes: Attributes5
    relationships: NotRequired[Relationships7]


class ZtpDeviceCreateRequest(TypedDict):
    data: Data10


class Attributes6(TypedDict):
    label: NotRequired[str | None]


class Relationships8(TypedDict):
    customer: NotRequired[Customer3]


class Data11(TypedDict):
    type: Literal['ztp-devices']
    id: str
    attributes: NotRequired[Attributes6]
    relationships: NotRequired[Relationships8]


class ZtpDeviceUpdateRequest(TypedDict):
    data: Data11


PortOrderStatus: TypeAlias = Literal[
    'draft',
    'awaiting_signature',
    'awaiting_review',
    'submitted',
    'foc_assigned',
    'completed',
    'failed',
]


PortNumberFailureCause: TypeAlias = Literal['withdrawn', 'carrier_refused'] | None


PortDocumentKind: TypeAlias = Literal['loa', 'bill']


PortType: TypeAlias = Literal['full', 'partial'] | None


PortNumberType: TypeAlias = Literal['landline', 'wireless', 'voip'] | None


PortOrderTaskBillState: TypeAlias = Literal['missing', 'received']


PortOrderTaskDateState: TypeAlias = Literal['missing', 'chosen']


PortOrderTaskSignatureState: TypeAlias = Literal['not_ready', 'ready', 'signed']


PortOrderBillExtractionStatus: TypeAlias = Literal[
    'pending', 'done', 'failed', 'skipped'
]


PortOrderRequestLinkMailKind: TypeAlias = Literal['bill', 'signature']


class PortOrderNumberState(TypedDict):
    e164: NotRequired[str | None]
    status: NotRequired[PortOrderStatus]
    cause: NotRequired[PortNumberFailureCause]
    focDate: NotRequired[str | None]
    stopped: NotRequired[bool]
    stoppedSince: NotRequired[str | None]


class PortOrderDocumentSlot(TypedDict):
    sha256: NotRequired[str]
    uploadedAt: NotRequired[str | None]


class PortOrderDocuments(TypedDict):
    loa: NotRequired[PortOrderDocumentSlot | None]
    bill: NotRequired[PortOrderDocumentSlot | None]


class PortOrderUnsignedLoa(TypedDict):
    sha256: NotRequired[str]
    generatedAt: NotRequired[str | None]


class PortOrderRequestLinkState(TypedDict):
    active: NotRequired[bool]


class PortOrderTasks(TypedDict):
    bill: NotRequired[PortOrderTaskBillState]
    date: NotRequired[PortOrderTaskDateState]
    signature: NotRequired[PortOrderTaskSignatureState]


class PortOrderBillExtraction(TypedDict):
    status: NotRequired[PortOrderBillExtractionStatus]
    fields: NotRequired[list[str]]
    extractedAt: NotRequired[str | None]


class PortOrderAttributes(TypedDict):
    label: NotRequired[str]
    country: NotRequired[str]
    status: NotRequired[PortOrderStatus]
    endUserName: NotRequired[str | None]
    endUserAddress: NotRequired[str | None]
    loaSigner: NotRequired[str | None]
    loaDate: NotRequired[str | None]
    currentProvider: NotRequired[str | None]
    accountNumber: NotRequired[str | None]
    monthlyMou: NotRequired[int]
    accountPin: NotRequired[None]
    accountPinAttestedNone: NotRequired[bool]
    billingPhone: NotRequired[str | None]
    portType: NotRequired[PortType]
    newBillingNumber: NotRequired[str | None]
    serviceStreetNumber: NotRequired[str | None]
    serviceStreetName: NotRequired[str | None]
    serviceCity: NotRequired[str | None]
    serviceState: NotRequired[str | None]
    serviceZip: NotRequired[str | None]
    requestedFocDate: NotRequired[str | None]
    contactName: NotRequired[str | None]
    contactTitle: NotRequired[str | None]
    contactEmail: NotRequired[str | None]
    contactPhone: NotRequired[str | None]
    numbersNotTransferring: NotRequired[str | None]
    numbers: NotRequired[list[str]]
    correctionsRequired: NotRequired[bool]
    correctionsNote: NotRequired[str | None]
    numberStates: NotRequired[list[PortOrderNumberState]]
    documents: NotRequired[PortOrderDocuments]
    unsignedLoa: NotRequired[PortOrderUnsignedLoa | None]
    requestLink: NotRequired[PortOrderRequestLinkState]
    tasks: NotRequired[PortOrderTasks]
    detailsConfirmedAt: NotRequired[str | None]
    signatureRequestedAt: NotRequired[str | None]
    billExtraction: NotRequired[PortOrderBillExtraction | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class PortOrderResource(TypedDict):
    type: Literal['port-orders']
    id: str
    attributes: NotRequired[PortOrderAttributes]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class PortOrderDocumentResponse(TypedDict):
    data: PortOrderResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class PortOrderCollectionDocument(TypedDict):
    data: list[PortOrderResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes7(TypedDict):
    label: str
    country: NotRequired[str]


class Data12(TypedDict):
    type: Literal['port-orders']
    attributes: Attributes7


class PortOrderCreateRequest(TypedDict):
    data: Data12


class PortOrderNumberInput1(TypedDict):
    e164: str
    numberType: NotRequired[PortNumberType]


PortOrderNumberInput: TypeAlias = str | PortOrderNumberInput1


class Attributes8(TypedDict):
    label: NotRequired[str | None]
    endUserName: NotRequired[str | None]
    endUserAddress: NotRequired[str | None]
    loaSigner: NotRequired[str | None]
    loaDate: NotRequired[str | None]
    currentProvider: NotRequired[str | None]
    accountNumber: NotRequired[str | None]
    monthlyMou: NotRequired[int | None]
    accountPin: NotRequired[str | None]
    accountPinAttestedNone: NotRequired[bool]
    billingPhone: NotRequired[str | None]
    portType: NotRequired[PortType]
    newBillingNumber: NotRequired[str | None]
    serviceStreetNumber: NotRequired[str | None]
    serviceStreetName: NotRequired[str | None]
    serviceCity: NotRequired[str | None]
    serviceState: NotRequired[str | None]
    serviceZip: NotRequired[str | None]
    requestedFocDate: NotRequired[str | None]
    contactName: NotRequired[str | None]
    contactTitle: NotRequired[str | None]
    contactEmail: NotRequired[str | None]
    contactPhone: NotRequired[str | None]
    numbersNotTransferring: NotRequired[str | None]
    numbers: NotRequired[list[PortOrderNumberInput] | None]


class Data13(TypedDict):
    type: Literal['port-orders']
    id: str
    attributes: NotRequired[Attributes8]


class PortOrderUpdateRequest(TypedDict):
    data: Data13


class PortOrderDocumentUploadRequest(TypedDict):
    kind: PortDocumentKind
    file: bytes
    signed_on: NotRequired[str]
    signer: NotRequired[str]


class Data14(TypedDict):
    id: NotRequired[str]
    status: NotRequired[PortOrderStatus]
    numbers: NotRequired[list[str]]


class PortOrderSubmitted(TypedDict):
    data: Data14


class Data15(TypedDict):
    id: NotRequired[str]
    kind: NotRequired[PortDocumentKind]
    sha256: NotRequired[str | None]


class PortOrderDocumentStored(TypedDict):
    data: Data15


class Data16(TypedDict):
    id: NotRequired[str]
    sha256: NotRequired[str | None]


class PortOrderLoaGenerated(TypedDict):
    data: Data16


class Data17(TypedDict):
    id: NotRequired[str]
    url: NotRequired[str]


class PortOrderRequestLinkIssued(TypedDict):
    data: Data17


class Data18(TypedDict):
    id: NotRequired[str]
    revoked: NotRequired[bool]


class PortOrderRequestLinkRevoked(TypedDict):
    data: Data18


class PortOrderRequestLinkSendRequest(TypedDict):
    to: str
    kind: NotRequired[PortOrderRequestLinkMailKind]
    note: NotRequired[str | None]


class Data19(TypedDict):
    id: NotRequired[str]
    sent_to: NotRequired[str]


class PortOrderRequestLinkSent(TypedDict):
    data: Data19


CustomerRegionPreference: TypeAlias = Literal['partner_default', 'use1', 'usw1']


CustomerTransport: TypeAlias = Literal['udp', 'tcp', 'tls']


class CustomerAttributes(TypedDict):
    name: NotRequired[str]
    code: NotRequired[str | None]
    country: NotRequired[str | None]
    addressLines: NotRequired[list[str]]
    city: NotRequired[str | None]
    region: NotRequired[str | None]
    postalCode: NotRequired[str | None]
    timeZone: NotRequired[str | None]
    dataResidencyCountry: NotRequired[str]
    regionPreference: NotRequired[CustomerRegionPreference]
    effectiveRegion: NotRequired[str]
    pbx: NotRequired[bool]
    residential: NotRequired[bool | None]
    callLimit: NotRequired[int | None]
    callLimitExternal: NotRequired[int | None]
    transports: NotRequired[list[CustomerTransport] | None]
    provisioningState: NotRequired[ProvisioningState | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class CustomerResource(TypedDict):
    type: Literal['customers']
    id: str
    attributes: NotRequired[CustomerAttributes]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class CustomerDocumentResponse(TypedDict):
    data: CustomerResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class CustomerCollectionDocument(TypedDict):
    data: list[CustomerResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


TenantStatus: TypeAlias = Literal[
    'pending_email',
    'pending_kyc',
    'kyc_in_progress',
    'kyc_in_review',
    'active',
    'kyc_declined',
    'suspended',
]


class WhiteLabelDomain(TypedDict):
    registrableDomain: NotRequired[str]
    consoleHost: NotRequired[str]
    apiHost: NotRequired[str]
    status: NotRequired[
        Literal[
            'pending_dns', 'provisioning', 'verifying', 'active', 'failed', 'disabled'
        ]
    ]
    isPrimary: NotRequired[bool]


class SendingIdentity(TypedDict):
    address: NotRequired[str]
    status: NotRequired[
        Literal['pending', 'dns_pending', 'verifying', 'active', 'failed', 'disabled']
    ]


class TenantAttributes(TypedDict):
    brandName: NotRequired[str | None]
    legalName: NotRequired[str | None]
    status: NotRequired[TenantStatus]
    createdAt: NotRequired[str | None]
    onboardingRequirements: NotRequired[list[str]]
    brandColorPrimary: NotRequired[str | None]
    brandColorAccent: NotRequired[str | None]
    supportEmail: NotRequired[str | None]
    supportPhone: NotRequired[str | None]
    includedDomain: NotRequired[str | None]
    whiteLabelDomain: NotRequired[WhiteLabelDomain | None]
    sendingIdentity: NotRequired[SendingIdentity | None]


class TenantResource(TypedDict):
    type: Literal['tenants']
    id: str
    attributes: NotRequired[TenantAttributes]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class TenantDocumentResponse(TypedDict):
    data: TenantResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class TenantWritableAttributes(TypedDict):
    brandColorPrimary: NotRequired[str | None]
    brandColorAccent: NotRequired[str | None]
    supportEmail: NotRequired[str | None]
    supportPhone: NotRequired[str | None]


class Data20(TypedDict):
    type: Literal['tenants']
    id: str
    attributes: TenantWritableAttributes


class TenantUpdateRequest(TypedDict):
    data: Data20


SipTrunkMode: TypeAlias = Literal['static', 'register']


SipTrunkRegistrationMode: TypeAlias = Literal['replace', 'additive']


SipTrunkLocalization: TypeAlias = Literal['US', 'CA', 'MX', 'GB']


SipTrunkAniFormat: TypeAlias = Literal[
    'plus_e164', 'e164', 'national', 'plus_e164_national', 'e164_national'
]


SipTrunkDnisFormat: TypeAlias = Literal['plus_e164', 'e164', 'national', 'sip_username']


SipTrunkDialPolicy: TypeAlias = Literal['us_canada', 'nanp', 'permit_all']


SipTrunkMediaMode: TypeAlias = Literal['anchored', 'direct']


SipTrunkTransport: TypeAlias = Literal['udp', 'tcp', 'tls']


class SipTrunkRegistration(TypedDict):
    state: NotRequired[Literal['registered', 'not_registered']]
    contacts: NotRequired[int]
    expires_at: NotRequired[str | None]


class SipTrunkAttributes(TypedDict):
    name: NotRequired[str]
    domainLabel: NotRequired[str]
    primaryRegion: NotRequired[Literal['use1', 'usw1']]
    enabled: NotRequired[bool]
    mode: NotRequired[SipTrunkMode]
    username: NotRequired[str | None]
    password: NotRequired[str | None]
    registrationMode: NotRequired[SipTrunkRegistrationMode]
    registrationExpires: NotRequired[int]
    localization: NotRequired[SipTrunkLocalization]
    aniFormat: NotRequired[SipTrunkAniFormat]
    dnisFormat: NotRequired[SipTrunkDnisFormat]
    dialPolicy: NotRequired[SipTrunkDialPolicy]
    mediaMode: NotRequired[SipTrunkMediaMode]
    codecs: NotRequired[list[Literal['PCMU', 'PCMA', 'G722']]]
    registration: NotRequired[SipTrunkRegistration | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class SipTrunkRelationships(TypedDict):
    customer: NotRequired[RelationshipToOne]
    callerIdOverride: NotRequired[RelationshipToOne]
    emergencyCallerId: NotRequired[RelationshipToOne]
    sipTrunkIps: NotRequired[RelationshipToMany]
    sipTrunkTargets: NotRequired[RelationshipToMany]


class SipTrunkResource(TypedDict):
    type: Literal['sip-trunks']
    id: str
    attributes: NotRequired[SipTrunkAttributes]
    relationships: NotRequired[SipTrunkRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class SipTrunkDocumentResponse(TypedDict):
    data: SipTrunkResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class SipTrunkCollectionDocument(TypedDict):
    data: list[SipTrunkResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class SipTrunkWritableAttributes(TypedDict):
    name: NotRequired[str]
    domainLabel: NotRequired[str]
    primaryRegion: NotRequired[Literal['use1', 'usw1']]
    enabled: NotRequired[bool]
    mode: NotRequired[SipTrunkMode]
    username: NotRequired[str | None]
    password: NotRequired[str | None]
    registrationMode: NotRequired[SipTrunkRegistrationMode]
    registrationExpires: NotRequired[int]
    localization: NotRequired[SipTrunkLocalization]
    aniFormat: NotRequired[SipTrunkAniFormat]
    dnisFormat: NotRequired[SipTrunkDnisFormat]
    dialPolicy: NotRequired[SipTrunkDialPolicy]
    mediaMode: NotRequired[SipTrunkMediaMode]
    codecs: NotRequired[list[Literal['PCMU', 'PCMA', 'G722']]]


class SipTrunkCreateAttributes(TypedDict):
    name: str
    domainLabel: str
    primaryRegion: Literal['use1', 'usw1']
    enabled: NotRequired[bool]
    mode: SipTrunkMode
    username: NotRequired[str | None]
    password: NotRequired[str | None]
    registrationMode: NotRequired[SipTrunkRegistrationMode]
    registrationExpires: NotRequired[int]
    localization: NotRequired[SipTrunkLocalization]
    aniFormat: NotRequired[SipTrunkAniFormat]
    dnisFormat: NotRequired[SipTrunkDnisFormat]
    dialPolicy: NotRequired[SipTrunkDialPolicy]
    mediaMode: NotRequired[SipTrunkMediaMode]
    codecs: NotRequired[list[Literal['PCMU', 'PCMA', 'G722']]]


class Customer5(TypedDict):
    data: ResourceIdentifier


class Relationships9(TypedDict):
    customer: Customer5


class Data21(TypedDict):
    type: Literal['sip-trunks']
    attributes: SipTrunkCreateAttributes
    relationships: Relationships9


class SipTrunkCreateRequest(TypedDict):
    data: Data21


class Data22(TypedDict):
    type: Literal['sip-trunks']
    id: str
    attributes: SipTrunkWritableAttributes


class SipTrunkUpdateRequest(TypedDict):
    data: Data22


class SipTrunkIpAttributes(TypedDict):
    cidr: NotRequired[str]
    description: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class SipTrunkIpRelationships(TypedDict):
    sipTrunk: NotRequired[RelationshipToOne]


class SipTrunkIpResource(TypedDict):
    type: Literal['sip-trunk-ips']
    id: str
    attributes: NotRequired[SipTrunkIpAttributes]
    relationships: NotRequired[SipTrunkIpRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class SipTrunkIpDocumentResponse(TypedDict):
    data: SipTrunkIpResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class SipTrunkIpCollectionDocument(TypedDict):
    data: list[SipTrunkIpResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class SipTrunkIpWritableAttributes(TypedDict):
    cidr: NotRequired[str]
    description: NotRequired[str | None]


class SipTrunkIpCreateAttributes(TypedDict):
    cidr: str
    description: NotRequired[str | None]


class SipTrunk(TypedDict):
    data: ResourceIdentifier


class Relationships10(TypedDict):
    sipTrunk: SipTrunk


class Data23(TypedDict):
    type: Literal['sip-trunk-ips']
    attributes: SipTrunkIpCreateAttributes
    relationships: Relationships10


class SipTrunkIpCreateRequest(TypedDict):
    data: Data23


class Data24(TypedDict):
    type: Literal['sip-trunk-ips']
    id: str
    attributes: SipTrunkIpWritableAttributes


class SipTrunkIpUpdateRequest(TypedDict):
    data: Data24


class SipTrunkTargetAttributes(TypedDict):
    host: NotRequired[str]
    port: NotRequired[int | None]
    transport: NotRequired[SipTrunkTransport]
    preference: NotRequired[int]
    enabled: NotRequired[bool]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class SipTrunkTargetRelationships(TypedDict):
    sipTrunk: NotRequired[RelationshipToOne]


class SipTrunkTargetResource(TypedDict):
    type: Literal['sip-trunk-targets']
    id: str
    attributes: NotRequired[SipTrunkTargetAttributes]
    relationships: NotRequired[SipTrunkTargetRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class SipTrunkTargetDocumentResponse(TypedDict):
    data: SipTrunkTargetResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class SipTrunkTargetCollectionDocument(TypedDict):
    data: list[SipTrunkTargetResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class SipTrunkTargetWritableAttributes(TypedDict):
    host: NotRequired[str]
    port: NotRequired[int | None]
    transport: NotRequired[SipTrunkTransport]
    preference: NotRequired[int]
    enabled: NotRequired[bool]


class SipTrunkTargetCreateAttributes(TypedDict):
    host: str
    port: NotRequired[int | None]
    transport: SipTrunkTransport
    preference: int
    enabled: bool


class Relationships11(TypedDict):
    sipTrunk: SipTrunk


class Data25(TypedDict):
    type: Literal['sip-trunk-targets']
    attributes: SipTrunkTargetCreateAttributes
    relationships: Relationships11


class SipTrunkTargetCreateRequest(TypedDict):
    data: Data25


class Data26(TypedDict):
    type: Literal['sip-trunk-targets']
    id: str
    attributes: SipTrunkTargetWritableAttributes


class SipTrunkTargetUpdateRequest(TypedDict):
    data: Data26


CallDirection: TypeAlias = Literal['inbound', 'outbound', 'onNet']


CallDisposition: TypeAlias = Literal['answered', 'missed']


class PbxCallRequestAttributes(TypedDict):
    destination: str
    callerId: NotRequired[str | None]
    autoAnswer: NotRequired[bool]
    device: NotRequired[str | None]


class PbxCallAttributes(TypedDict):
    destination: NotRequired[str]
    callerId: NotRequired[str | None]
    autoAnswer: NotRequired[bool]
    device: NotRequired[str | None]
    status: NotRequired[Literal['requested']]
    requestedAt: NotRequired[str]


class PbxCallResource(TypedDict):
    type: Literal['calls']
    id: str
    attributes: NotRequired[PbxCallAttributes]


class PbxCallDocumentResponse(TypedDict):
    data: PbxCallResource


class PbxUserAttributes(TypedDict):
    user: NotRequired[str | None]
    domain: NotRequired[str | None]
    displayName: NotRequired[str | None]
    firstName: NotRequired[str | None]
    lastName: NotRequired[str | None]
    email: NotRequired[str | None]
    scope: NotRequired[str | None]
    group: NotRequired[str | None]
    site: NotRequired[str | None]
    presence: NotRequired[str | None]
    callerIdNumber: NotRequired[str | None]
    callerIdName: NotRequired[str | None]
    timeZone: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class PbxUserRelationships(TypedDict):
    customer: NotRequired[RelationshipToOne]
    devices: NotRequired[RelationshipToMany]


class PbxUserResource(TypedDict):
    type: Literal['users']
    id: str
    attributes: NotRequired[PbxUserAttributes]
    relationships: NotRequired[PbxUserRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class PbxUserDocumentResponse(TypedDict):
    data: PbxUserResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class PbxUserCollectionDocument(TypedDict):
    data: list[PbxUserResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class PbxDeviceAttributes(TypedDict):
    aor: NotRequired[str | None]
    user: NotRequired[str | None]
    domain: NotRequired[str | None]
    mode: NotRequired[str | None]
    userAgent: NotRequired[str | None]
    contact: NotRequired[str | None]
    transport: NotRequired[str | None]
    receivedFrom: NotRequired[str | None]
    registeredAt: NotRequired[str | None]
    registrationExpiresAt: NotRequired[str | None]
    registered: NotRequired[bool]
    autoAnswer: NotRequired[bool]
    createdAt: NotRequired[str | None]


class PbxDeviceRelationships(TypedDict):
    customer: NotRequired[RelationshipToOne]
    pbxUser: NotRequired[RelationshipToOne]


class PbxDeviceResource(TypedDict):
    type: Literal['devices']
    id: str
    attributes: NotRequired[PbxDeviceAttributes]
    relationships: NotRequired[PbxDeviceRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class PbxDeviceDocumentResponse(TypedDict):
    data: PbxDeviceResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class PbxDeviceCollectionDocument(TypedDict):
    data: list[PbxDeviceResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class CallRecordAttributes(TypedDict):
    direction: NotRequired[CallDirection]
    disposition: NotRequired[CallDisposition]
    tenantId: NotRequired[str | None]
    domain: NotRequired[str | None]
    territory: NotRequired[str | None]
    fromNumber: NotRequired[str | None]
    fromExtension: NotRequired[str | None]
    fromName: NotRequired[str | None]
    toNumber: NotRequired[str | None]
    dialedNumber: NotRequired[str | None]
    routedByExtension: NotRequired[str | None]
    answeringExtension: NotRequired[str | None]
    startedAt: NotRequired[str | None]
    answeredAt: NotRequired[str | None]
    releasedAt: NotRequired[str | None]
    durationSeconds: NotRequired[int | None]
    talkSeconds: NotRequired[int | None]
    releaseCode: NotRequired[str | None]
    releaseText: NotRequired[str | None]
    hasRecording: NotRequired[bool]
    hidden: NotRequired[bool]
    vendorId: NotRequired[str | None]
    origCallId: NotRequired[str | None]
    termCallId: NotRequired[str | None]
    byAction: NotRequired[str | None]
    terminatedTo: NotRequired[str | None]
    codec: NotRequired[str | None]
    hostname: NotRequired[str | None]
    rawFromUri: NotRequired[str | None]
    rawFromUser: NotRequired[str | None]
    rawToUser: NotRequired[str | None]
    rawRequestUser: NotRequired[str | None]


class CallRecordRelationships(TypedDict):
    customer: NotRequired[RelationshipToOne]
    fromPbxUser: NotRequired[RelationshipToOne]
    toPbxUser: NotRequired[RelationshipToOne]


class CallRecordResource(TypedDict):
    type: Literal['call-records']
    id: str
    attributes: NotRequired[CallRecordAttributes]
    relationships: NotRequired[CallRecordRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


RecordingAttributes = TypedDict(
    'RecordingAttributes',
    {
        'ccc-id': NotRequired[str],
        'duration': NotRequired[int | None],
        'byte-size': NotRequired[int],
        'sha256': NotRequired[str],
        'superseded': NotRequired[bool],
        'content-url': NotRequired[str],
        'expires-at': NotRequired[str],
    },
)


class RecordingResource(TypedDict):
    type: Literal['recordings']
    id: str
    attributes: NotRequired[RecordingAttributes]


class RecordingCollectionDocument(TypedDict):
    data: list[RecordingResource]


class TranscriptSegment(TypedDict):
    speaker: str
    start: float
    end: float
    text: str


TranscriptAttributes = TypedDict(
    'TranscriptAttributes',
    {
        'ccc-id': NotRequired[str],
        'status': NotRequired[Literal['ready', 'pending']],
        'language': NotRequired[str | None],
        'duration': NotRequired[int | None],
        'byte-size': NotRequired[int | None],
        'sha256': NotRequired[str | None],
        'provider': NotRequired[str | None],
        'model': NotRequired[str | None],
        'content-url': NotRequired[str | None],
        'expires-at': NotRequired[str | None],
    },
)


class TranscriptResource(TypedDict):
    type: Literal['transcripts']
    id: str
    attributes: NotRequired[TranscriptAttributes]


Attributes9 = TypedDict(
    'Attributes9',
    {
        'ccc-id': NotRequired[str],
        'status': NotRequired[Literal['ready', 'pending']],
        'language': NotRequired[str | None],
        'duration': NotRequired[int | None],
        'byte-size': NotRequired[int | None],
        'sha256': NotRequired[str | None],
        'provider': NotRequired[str | None],
        'model': NotRequired[str | None],
        'content-url': NotRequired[str | None],
        'expires-at': NotRequired[str | None],
        'segments': NotRequired[list[TranscriptSegment]],
    },
)


class TranscriptWithSegmentsResource(TranscriptResource):
    attributes: NotRequired[Attributes9]


class TranscriptCollectionDocument(TypedDict):
    data: list[TranscriptResource]


class TranscriptDocumentResponse(TypedDict):
    data: TranscriptWithSegmentsResource


class CallRecordDocumentResponse(TypedDict):
    data: CallRecordResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class CallRecordCollectionDocument(TypedDict):
    data: list[CallRecordResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Error(TypedDict):
    status: str
    title: NotRequired[str]
    detail: NotRequired[str]
    code: NotRequired[ErrorCode]
    source: NotRequired[ErrorSource]
    meta: NotRequired[dict[str, Any]]


class ErrorDocument(TypedDict):
    errors: list[Error]


class Attributes1(TypedDict):
    e164: NotRequired[str | None]
    status: NotRequired[Literal['pending', 'active', 'failed', 'releasing'] | None]
    country: NotRequired[str | None]
    activatedAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    messaging: NotRequired[PhoneNumberMessaging]
    voice: NotRequired[PhoneNumberVoice]


class PhoneNumberResource(TypedDict):
    type: Literal['phone-numbers']
    id: str
    attributes: NotRequired[Attributes1]
    relationships: NotRequired[Relationships3]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class PhoneNumberCollectionDocument(TypedDict):
    data: list[PhoneNumberResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


MessageReceivedEventData = TypedDict(
    'MessageReceivedEventData',
    {
        'id': NotRequired[str],
        'tenant_id': NotRequired[str],
        'customer_id': NotRequired[str | None],
        'kind': NotRequired[InboundMessageKind],
        'from': NotRequired[str],
        'to': NotRequired[str],
        'body': NotRequired[str | None],
        'media': NotRequired[list[InboundMessageMediaPart]],
        'received_at': NotRequired[str],
    },
)


PortOrderStatusChangedEventData = TypedDict(
    'PortOrderStatusChangedEventData',
    {
        'port_order_id': NotRequired[str],
        'tenant_id': NotRequired[str],
        'from': NotRequired[PortOrderStatus],
        'to': NotRequired[PortOrderStatus],
    },
)


class PortOrderBillExtractionSettledEventData(TypedDict):
    port_order_id: NotRequired[str]
    tenant_id: NotRequired[str]
    status: NotRequired[PortOrderBillExtractionStatus]


class MessageReceivedEvent(WebhookEventEnvelope):
    data: MessageReceivedEventData


class PortOrderStatusChangedEvent(WebhookEventEnvelope):
    data: PortOrderStatusChangedEventData


class PortOrderBillExtractionSettledEvent(WebhookEventEnvelope):
    data: PortOrderBillExtractionSettledEventData


class Data27(TypedDict):
    type: Literal['calls']
    attributes: PbxCallRequestAttributes


class PbxCallRequest(TypedDict):
    data: Data27
