"""The vendored spec's schemas, as types. Machine-written — do not edit.

Each `TypedDict` below describes one JSON shape from spec/openapi.yaml, and
describes it at TYPE-CHECK TIME ONLY: a `TypedDict` is a plain `dict` at
runtime, so this module defines no behaviour and constructs nothing. It is
not imported by `ringivo/__init__.py`, so it costs an ordinary caller
nothing.

Nothing generated crosses the public boundary — `models.py` owns the frozen
objects this client hands back, and it reads the wire defensively rather
than trusting these shapes. What these types are FOR is reading: they are
the machine-checked record of what the API sends and accepts, for anyone
reaching past the wrapped surface with `Ringivo.request()`.

Regenerate with scripts/generate.sh, which overwrites this file whole.
"""
from __future__ import annotations

#
# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   version:   0.74.0

from typing import Any, Literal, TypeAlias

from typing_extensions import NotRequired, TypedDict


class OauthTokenRequest(TypedDict):
    grant_type: Literal['client_credentials']
    client_id: NotRequired[str]
    client_secret: NotRequired[str]
    tenant: NotRequired[str]
    customer: NotRequired[str | None]
    scope: NotRequired[str]


class OauthTokenResponse(TypedDict):
    access_token: str
    token_type: str
    expires_in: int
    scope: str
    scopes: list[str]


class OauthError(TypedDict):
    error: str
    error_description: str
    hint: NotRequired[str]


class IntegrationTokenRequest(TypedDict):
    client_id: NotRequired[str]
    client_secret: NotRequired[str]
    tenant: NotRequired[str]
    customer: NotRequired[str | None]
    scopes: NotRequired[list[str]]
    scope: NotRequired[str | None]


class IntegrationTokenResponse(TypedDict):
    access_token: str
    token_type: str
    expires_in: int
    scopes: list[str]


class ResourceIdentifier(TypedDict):
    type: str
    id: str


class ResourceLinks(TypedDict):
    self: NotRequired[str]


class CollectionLinks(TypedDict):
    self: NotRequired[str | None]
    first: NotRequired[str]
    prev: NotRequired[str]
    next: NotRequired[str]


class PageMeta(TypedDict):
    size: int
    nextCursor: str | None
    total: NotRequired[int]


class DocumentMeta(TypedDict):
    page: NotRequired[PageMeta]


class Page(TypedDict):
    cursor: NotRequired[str]


class ResourceMeta(TypedDict):
    page: NotRequired[Page]


class RelationshipToOne(TypedDict):
    links: NotRequired[ResourceLinks]
    data: NotRequired[ResourceIdentifier | None]


class RelationshipToMany(TypedDict):
    links: NotRequired[ResourceLinks]
    data: NotRequired[list[ResourceIdentifier]]


class ErrorSource(TypedDict):
    pointer: NotRequired[str]
    parameter: NotRequired[str]


ErrorCode: TypeAlias = Literal[
    'validation_failed',
    'caller_id_not_permitted',
    'document_too_large',
    'too_many_pages',
    'unsupported_media_type',
    'fax_account_suspended',
    'rate_limited',
    'not_found',
    'forbidden',
    'internal_error',
]


FaxDirection: TypeAlias = Literal['inbound', 'outbound']


FaxStatus: TypeAlias = Literal[
    'queued',
    'converting',
    'sending',
    'delivered',
    'partial',
    'cancelled',
    'received',
    'failed',
]


FaxFailureCode: TypeAlias = (
    Literal[
        'busy',
        'no_answer',
        'no_fax_tone',
        'negotiation_failed',
        'line_quality',
        'line_dropped',
        'incompatible',
        'document_error',
        'invalid_number',
        'carrier_rejected',
        'internal_error',
    ]
    | None
)


FaxAccountStatus: TypeAlias = Literal['active', 'suspended']


FaxResolution: TypeAlias = Literal['fine', 'standard']


WebhookScopeType: TypeAlias = Literal['tenant', 'customer', 'fax_account']


WebhookEventType: TypeAlias = Literal[
    'fax.received',
    'fax.queued',
    'fax.converting',
    'fax.sending',
    'fax.delivered',
    'fax.partial',
    'fax.failed',
    'fax.cancelled',
]


WebhookDeliveryStatus: TypeAlias = Literal['pending', 'delivered', 'dead']


Tags: TypeAlias = dict[str, Any] | None


CoverPage: TypeAlias = dict[str, Any] | None


class FaxDocumentMetadata(TypedDict):
    kind: NotRequired[Literal['source', 'tiff', 'pdf', 'thumb']]
    ordinal: NotRequired[int]
    contentType: NotRequired[str | None]
    byteSize: NotRequired[int | None]
    sha256: NotRequired[str | None]
    pages: NotRequired[int | None]


FaxAttributes = TypedDict(
    'FaxAttributes',
    {
        'direction': NotRequired[FaxDirection],
        'status': NotRequired[FaxStatus],
        'failureCode': NotRequired[FaxFailureCode],
        'from': NotRequired[str | None],
        'to': NotRequired[str | None],
        'pagesTotal': NotRequired[int | None],
        'pagesTransferred': NotRequired[int | None],
        'partial': NotRequired[bool | None],
        'attemptCount': NotRequired[int | None],
        'resolution': NotRequired[str | None],
        'clientReference': NotRequired[str | None],
        'coverPage': NotRequired[CoverPage],
        'read': NotRequired[bool],
        'archived': NotRequired[bool],
        'tags': NotRequired[Tags],
        'documents': NotRequired[list[FaxDocumentMetadata]],
        'createdAt': NotRequired[str | None],
        'completedAt': NotRequired[str | None],
    },
)


class FaxRelationships(TypedDict):
    faxAccount: NotRequired[RelationshipToOne]
    attempts: NotRequired[RelationshipToMany]


class FaxResource(TypedDict):
    type: Literal['faxes']
    id: str
    attributes: NotRequired[FaxAttributes]
    relationships: NotRequired[FaxRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class FaxAttemptAttributes(TypedDict):
    attemptNo: NotRequired[int | None]
    transportProfile: NotRequired[dict[str, Any] | None]
    startedAt: NotRequired[str | None]
    answeredAt: NotRequired[str | None]
    endedAt: NotRequired[str | None]
    billableMs: NotRequired[int | None]
    hangupCause: NotRequired[str | None]
    sipStatus: NotRequired[int | None]
    faxSuccess: NotRequired[bool | None]
    faxResultCode: NotRequired[int | None]
    faxResultText: NotRequired[str | None]
    pagesTransferred: NotRequired[int | None]
    pagesTotal: NotRequired[int | None]
    transferRate: NotRequired[int | None]
    ecmUsed: NotRequired[bool | None]
    t38Used: NotRequired[bool | None]
    imageResolution: NotRequired[str | None]
    badRows: NotRequired[int | None]
    remoteStationId: NotRequired[str | None]


class FaxAttemptResource(TypedDict):
    type: Literal['fax-attempts']
    id: str
    attributes: NotRequired[FaxAttemptAttributes]
    links: NotRequired[ResourceLinks]


class FaxDocumentResponse(TypedDict):
    data: FaxResource
    included: NotRequired[list[FaxAttemptResource]]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class FaxCollectionDocument(TypedDict):
    data: list[FaxResource]
    included: NotRequired[list[FaxAttemptResource]]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes(TypedDict):
    read: NotRequired[bool]
    archived: NotRequired[bool]
    tags: NotRequired[Tags]


class Data(TypedDict):
    type: Literal['faxes']
    id: str
    attributes: NotRequired[Attributes]


class FaxUpdateRequest(TypedDict):
    data: Data


class CoverPageRequest(TypedDict):
    to_name: NotRequired[str]
    from_name: NotRequired[str]
    subject: NotRequired[str]
    message: NotRequired[str]


SendFaxMultipartRequest = TypedDict(
    'SendFaxMultipartRequest',
    {
        'fax_account': str,
        'to': str,
        'from': NotRequired[str],
        'resolution': NotRequired[FaxResolution],
        'cover_page': NotRequired[CoverPageRequest | None],
        'client_reference': NotRequired[str],
        'tags': NotRequired[Tags],
        'documents': list[bytes],
    },
)


SendFaxUrlRequest = TypedDict(
    'SendFaxUrlRequest',
    {
        'fax_account': str,
        'to': str,
        'from': NotRequired[str],
        'resolution': NotRequired[FaxResolution],
        'cover_page': NotRequired[CoverPageRequest | None],
        'client_reference': NotRequired[str],
        'tags': NotRequired[Tags],
        'documents': list[str],
    },
)


Data1 = TypedDict(
    'Data1',
    {
        'id': NotRequired[str],
        'status': NotRequired[FaxStatus],
        'direction': NotRequired[FaxDirection],
        'from': NotRequired[str | None],
        'to': NotRequired[str | None],
        'client_reference': NotRequired[str | None],
        'created_at': NotRequired[str | None],
    },
)


class SendFaxAccepted(TypedDict):
    data: Data1


class Data2(TypedDict):
    id: NotRequired[str]
    status: NotRequired[FaxStatus]


class CancelFaxResult(TypedDict):
    data: Data2


class MediaLink(TypedDict):
    url: str
    expires_at: str
    byte_size: int
    sha256: str


class FaxAccountAttributes(TypedDict):
    name: NotRequired[str]
    headerText: NotRequired[str | None]
    defaultFromE164: NotRequired[str | None]
    retentionDays: NotRequired[int]
    complianceRetention: NotRequired[bool]
    maxAttempts: NotRequired[int]
    status: NotRequired[FaxAccountStatus]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class FaxAccountRelationships(TypedDict):
    customer: NotRequired[RelationshipToOne]
    numbers: NotRequired[RelationshipToMany]


class FaxAccountResource(TypedDict):
    type: Literal['fax-accounts']
    id: str
    attributes: NotRequired[FaxAccountAttributes]
    relationships: NotRequired[FaxAccountRelationships]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class FaxAccountDocumentResponse(TypedDict):
    data: FaxAccountResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccountCollectionDocument(TypedDict):
    data: list[FaxAccountResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccountWritableAttributes(TypedDict):
    name: NotRequired[str]
    headerText: NotRequired[str | None]
    defaultFromE164: NotRequired[str | None]
    retentionDays: NotRequired[int]
    complianceRetention: NotRequired[bool]
    maxAttempts: NotRequired[int]
    status: NotRequired[FaxAccountStatus]


class Customer(TypedDict):
    data: ResourceIdentifier


class Relationships(TypedDict):
    customer: Customer


class Data3(TypedDict):
    type: Literal['fax-accounts']
    attributes: FaxAccountWritableAttributes
    relationships: Relationships


class FaxAccountCreateRequest(TypedDict):
    data: Data3


class Data4(TypedDict):
    type: Literal['fax-accounts']
    id: str
    attributes: FaxAccountWritableAttributes


class FaxAccountUpdateRequest(TypedDict):
    data: Data4


class FaxAccountUserAttributes(TypedDict):
    userEmail: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class Relationships1(TypedDict):
    faxAccount: NotRequired[RelationshipToOne]
    user: NotRequired[RelationshipToOne]


class FaxAccountUserResource(TypedDict):
    type: Literal['fax-account-users']
    id: str
    attributes: NotRequired[FaxAccountUserAttributes]
    relationships: NotRequired[Relationships1]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class FaxAccountUserDocumentResponse(TypedDict):
    data: FaxAccountUserResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccountUserCollectionDocument(TypedDict):
    data: list[FaxAccountUserResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class FaxAccount(TypedDict):
    data: ResourceIdentifier


class User(TypedDict):
    data: ResourceIdentifier


class Relationships2(TypedDict):
    faxAccount: FaxAccount
    user: User


class Data5(TypedDict):
    type: Literal['fax-account-users']
    relationships: Relationships2


class FaxAccountUserCreateRequest(TypedDict):
    data: Data5


class Attributes1(TypedDict):
    e164: NotRequired[str | None]
    status: NotRequired[Literal['pending', 'active', 'failed', 'releasing'] | None]
    country: NotRequired[str | None]
    activatedAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]


class Relationships3(TypedDict):
    customer: NotRequired[RelationshipToOne]
    routingTarget: NotRequired[RelationshipToOne]
    pbxNumber: NotRequired[RelationshipToOne]


class PhoneNumberResource(TypedDict):
    type: Literal['phone-numbers']
    id: str
    attributes: NotRequired[Attributes1]
    relationships: NotRequired[Relationships3]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class PhoneNumberCollectionDocument(TypedDict):
    data: list[PhoneNumberResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class WebhookEndpointAttributes(TypedDict):
    scopeType: NotRequired[WebhookScopeType]
    scopeId: NotRequired[str | None]
    url: NotRequired[str | None]
    events: NotRequired[list[WebhookEventType] | None]
    active: NotRequired[bool | None]
    secret: NotRequired[str | None]
    secretPreviousExpiresAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class WebhookEndpointResource(TypedDict):
    type: Literal['webhook-endpoints']
    id: str
    attributes: NotRequired[WebhookEndpointAttributes]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class WebhookEndpointDocumentResponse(TypedDict):
    data: WebhookEndpointResource
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class WebhookEndpointCollectionDocument(TypedDict):
    data: list[WebhookEndpointResource]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


class Attributes2(TypedDict):
    url: str
    scopeType: WebhookScopeType
    scopeId: str
    events: NotRequired[list[WebhookEventType] | None]
    active: NotRequired[bool]


class Data6(TypedDict):
    type: Literal['webhook-endpoints']
    attributes: Attributes2


class WebhookEndpointCreateRequest(TypedDict):
    data: Data6


class Attributes3(TypedDict):
    url: str
    events: NotRequired[list[WebhookEventType] | None]
    active: NotRequired[bool]


class Data7(TypedDict):
    type: Literal['webhook-endpoints']
    id: str
    attributes: Attributes3


class WebhookEndpointUpdateRequest(TypedDict):
    data: Data7


class WebhookDeliveryAttributes(TypedDict):
    eventId: NotRequired[str | None]
    eventType: NotRequired[WebhookEventType]
    payloadSha256: NotRequired[str | None]
    status: NotRequired[WebhookDeliveryStatus]
    attemptNo: NotRequired[int | None]
    statusCode: NotRequired[int | None]
    durationMs: NotRequired[int | None]
    error: NotRequired[str | None]
    nextAttemptAt: NotRequired[str | None]
    deliveredAt: NotRequired[str | None]
    deadAt: NotRequired[str | None]
    createdAt: NotRequired[str | None]
    updatedAt: NotRequired[str | None]


class Relationships4(TypedDict):
    endpoint: NotRequired[RelationshipToOne]


class WebhookDeliveryResource(TypedDict):
    type: Literal['webhook-deliveries']
    id: str
    attributes: NotRequired[WebhookDeliveryAttributes]
    relationships: NotRequired[Relationships4]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[ResourceMeta]


class WebhookDeliveryDocumentResponse(TypedDict):
    data: WebhookDeliveryResource
    included: NotRequired[list[WebhookEndpointResource]]
    links: NotRequired[ResourceLinks]
    meta: NotRequired[DocumentMeta]


class WebhookDeliveryCollectionDocument(TypedDict):
    data: list[WebhookDeliveryResource]
    included: NotRequired[list[WebhookEndpointResource]]
    links: NotRequired[CollectionLinks]
    meta: NotRequired[DocumentMeta]


FaxEventData = TypedDict(
    'FaxEventData',
    {
        'id': NotRequired[str],
        'fax_account_id': NotRequired[str],
        'tenant_id': NotRequired[str],
        'customer_id': NotRequired[str | None],
        'direction': NotRequired[FaxDirection],
        'status': NotRequired[FaxStatus],
        'failure_code': NotRequired[FaxFailureCode],
        'from': NotRequired[str | None],
        'to': NotRequired[str | None],
        'region': NotRequired[str | None],
        'pages_total': NotRequired[int | None],
        'pages_transferred': NotRequired[int | None],
        'partial': NotRequired[bool | None],
        'attempt_count': NotRequired[int | None],
        'client_reference': NotRequired[str | None],
        'tags': NotRequired[Tags],
        'created_at': NotRequired[str | None],
        'completed_at': NotRequired[str | None],
    },
)


class FaxReceivedEventData(FaxEventData):
    render_failed: NotRequired[bool]


class WebhookEventEnvelope(TypedDict):
    event_id: str
    type: WebhookEventType
    occurred_at: str


class FaxEvent(WebhookEventEnvelope):
    data: FaxEventData


class FaxReceivedEvent(WebhookEventEnvelope):
    data: FaxReceivedEventData


class NumberLookupRequest(TypedDict, closed=True):
    number: str


NumberLookupDipStatus: TypeAlias = Literal['answered', 'no_data', 'failed']


class DialedNumberGeography(TypedDict):
    rateCenter: str | None
    state: str | None


class LrnFacts(TypedDict):
    lrn: str
    spid: str | None
    ocn: str | None
    lata: str | None
    lec: str | None
    lineType: str | None
    rateCenter: str | None
    state: str | None
    jurisdiction: str | None
    local: str | None
    portedAt: str | None


class CallerNameFacts(TypedDict):
    name: str


class MessagingFacts(TypedDict):
    enabled: bool
    provider: str | None
    country: str | None
    countryCode: str | None


class NumberLookupLrnComponent(TypedDict):
    status: NumberLookupDipStatus
    data: LrnFacts | None


class NumberLookupCallerNameComponent(TypedDict):
    status: NumberLookupDipStatus
    data: CallerNameFacts | None


class NumberLookupMessagingComponent(TypedDict):
    status: NumberLookupDipStatus
    data: MessagingFacts | None


class NumberLookupComponents(TypedDict):
    lrn: NumberLookupLrnComponent
    callerName: NumberLookupCallerNameComponent
    messaging: NumberLookupMessagingComponent


class NumberLookup(TypedDict):
    number: str
    lookedUpAt: str
    charged: bool
    dialedNumber: DialedNumberGeography
    components: NumberLookupComponents


class NumberLookupResult(TypedDict):
    data: NumberLookup


class Error(TypedDict):
    status: str
    title: str
    detail: NotRequired[str]
    code: NotRequired[ErrorCode]
    source: NotRequired[ErrorSource]
    meta: NotRequired[dict[str, Any]]


class ErrorDocument(TypedDict):
    errors: list[Error]
